// <auto-generated />
using System;
using InternalSEO.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace InternalSEO.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260907062134_AddTechnicalAudit")]
    partial class AddTechnicalAudit
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("InternalSEO.Domain.Entities.ActivityLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("ActorEmail")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ActorId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ActorRole")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValueSql("SYSDATETIMEOFFSET()");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("PayloadJson")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ProjectId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ActorId");

                    b.HasIndex("EntityType", "EntityId");

                    b.HasIndex("ProjectId", "CreatedAt");

                    b.ToTable("ActivityLogs", (string)null);
                });

            modelBuilder.Entity("InternalSEO.Domain.Entities.AuditIssue", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AffectedUrl")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<string>("AffectedUrlHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CrawlRunId")
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValueSql("SYSDATETIMEOFFSET()");

                    b.Property<long>("FirstSeenAt")
                        .HasColumnType("INTEGER");

                    b.Property<long>("LastSeenAt")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RuleCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("Open");

                    b.HasKey("Id");

                    b.HasIndex("RuleCode");

                    b.HasIndex("CrawlRunId", "RuleCode");

                    b.HasIndex("ProjectId", "Status", "Severity");

                    b.ToTable("AuditIssues", (string)null);
                });

            modelBuilder.Entity("InternalSEO.Domain.Entities.AuditRule", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("DefaultSeverity")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("Warning");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<string>("Recommendation")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("AuditRules", (string)null);
                });

            modelBuilder.Entity("InternalSEO.Domain.Entities.CrawlPage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CanonicalUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<long?>("ContentLengthBytes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ContentType")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("CrawlDepth")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("CrawlRunId")
                        .HasColumnType("TEXT");

                    b.Property<long>("CrawledAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValueSql("SYSDATETIMEOFFSET()");

                    b.Property<string>("H1")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("H1Count")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HttpStatusCode")
                        .HasColumnType("INTEGER");

                    b.Property<string>("IndexabilityStatus")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("InlinksCount")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsIndexable")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("LoadTimeMs")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MetaDescription")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<int>("OutlinksCount")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int?>("TitleLength")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<string>("UrlHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CrawlRunId", "UrlHash");

                    b.HasIndex("ProjectId", "UrlHash");

                    b.ToTable("CrawlPages", (string)null);
                });

            modelBuilder.Entity("InternalSEO.Domain.Entities.CrawlRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<long?>("CompletedAt")
                        .HasColumnType("INTEGER");

                    b.Property<long>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValueSql("SYSDATETIMEOFFSET()");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<int>("ErrorsCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FailureReason")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("HealthScore")
                        .HasPrecision(5, 2)
                        .HasColumnType("TEXT");

                    b.Property<int>("NoticesCount")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("TEXT");

                    b.Property<long?>("StartedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("Queued");

                    b.Property<string>("TriggerSource")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("Manual");

                    b.Property<int>("UrlsCrawled")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UrlsDiscovered")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WarningsCount")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("ProjectId", "CreatedAt");

                    b.ToTable("CrawlRuns", (string)null);
                });

            modelBuilder.Entity("InternalSEO.Domain.Entities.IssueEvidence", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValueSql("SYSDATETIMEOFFSET()");

                    b.Property<string>("EvidencePayload")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EvidenceType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("IssueId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IssueId");

                    b.ToTable("IssueEvidence", (string)null);
                });

            modelBuilder.Entity("InternalSEO.Domain.Entities.Keyword", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(2)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("US");

                    b.Property<decimal?>("CpcUsd")
                        .HasPrecision(8, 2)
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValueSql("SYSDATETIMEOFFSET()");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<string>("Device")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("desktop");

                    b.Property<Guid?>("GroupId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<decimal?>("KeywordDifficulty")
                        .HasPrecision(5, 2)
                        .HasColumnType("TEXT");

                    b.Property<string>("KeywordText")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<string>("LanguageCode")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(5)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("en");

                    b.Property<long?>("LastCheckedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LocationName")
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<int?>("MonthlySearchVolume")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NormalizedText")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SearchEngine")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("google");

                    b.Property<string>("SearchIntent")
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("TargetUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("GroupId");

                    b.HasIndex("ProjectId", "IsActive");

                    b.HasIndex("ProjectId", "NormalizedText", "SearchEngine", "CountryCode", "Device", "LocationName")
                        .IsUnique();

                    b.ToTable("Keywords", (string)null);
                });

            modelBuilder.Entity("InternalSEO.Domain.Entities.KeywordGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ColorHex")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(7)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("#3B82F6");

                    b.Property<long>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValueSql("SYSDATETIMEOFFSET()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId", "Name")
                        .IsUnique();

                    b.ToTable("KeywordGroups", (string)null);
                });

            modelBuilder.Entity("InternalSEO.Domain.Entities.KeywordTag", b =>
                {
                    b.Property<Guid>("KeywordId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TagId")
                        .HasColumnType("TEXT");

                    b.HasKey("KeywordId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("KeywordTags", (string)null);
                });

            modelBuilder.Entity("InternalSEO.Domain.Entities.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(2)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("US");

                    b.Property<long>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValueSql("SYSDATETIMEOFFSET()");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<string>("DefaultDevice")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("desktop");

                    b.Property<string>("DefaultSearchEngine")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("google");

                    b.Property<string>("Industry")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsArchived")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<string>("LanguageCode")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(5)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("en");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("PrimaryDomain")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("PrimaryLocation")
                        .HasColumnType("TEXT");

                    b.Property<string>("Protocol")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("https://");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Timezone")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("UTC");

                    b.Property<long>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValueSql("SYSDATETIMEOFFSET()");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("PrimaryDomain");

                    b.HasIndex("Status", "IsArchived");

                    b.ToTable("Projects", (string)null);
                });

            modelBuilder.Entity("InternalSEO.Domain.Entities.ProjectMember", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("AccessLevel")
                        .HasColumnType("INTEGER");

                    b.Property<long>("AssignedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValueSql("SYSDATETIMEOFFSET()");

                    b.Property<Guid>("AssignedBy")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("ProjectId", "UserId")
                        .IsUnique();

                    b.ToTable("ProjectMembers", (string)null);
                });

            modelBuilder.Entity("InternalSEO.Domain.Entities.ProjectSettings", b =>
                {
                    b.Property<Guid>("ProjectId")
                        .HasColumnType("TEXT");

                    b.Property<int>("CrawlConcurrency")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CrawlMaxDepth")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CrawlMaxPages")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CrawlRateLimitMs")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("CrawlRespectRobotsTxt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CrawlUserAgent")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("InternalSEOPlatformBot/1.0");

                    b.Property<string>("RankTrackingFrequency")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("Daily");

                    b.Property<TimeSpan>("RankTrackingTime")
                        .HasColumnType("TEXT");

                    b.Property<long>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValueSql("SYSDATETIMEOFFSET()");

                    b.HasKey("ProjectId");

                    b.ToTable("ProjectSettings", (string)null);
                });

            modelBuilder.Entity("InternalSEO.Domain.Entities.RankResult", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("CheckDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsCannibalized")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsTargetUrlMatched")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("KeywordId")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Position")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PositionChange")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PreviousPosition")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderName")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("development");

                    b.Property<string>("ProviderTaskId")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("RankedUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<string>("RawResponseRef")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<long>("RecordedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValueSql("SYSDATETIMEOFFSET()");

                    b.Property<string>("SerpFeatures")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("KeywordId", "CheckDate")
                        .IsUnique();

                    b.HasIndex("ProjectId", "CheckDate");

                    b.ToTable("RankResults", (string)null);
                });

            modelBuilder.Entity("InternalSEO.Domain.Entities.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValueSql("SYSDATETIMEOFFSET()");

                    b.Property<string>("Description")
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique();

                    b.ToTable("Roles", (string)null);
                });

            modelBuilder.Entity("InternalSEO.Domain.Entities.Tag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValueSql("SYSDATETIMEOFFSET()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId", "Name")
                        .IsUnique();

                    b.ToTable("Tags", (string)null);
                });

            modelBuilder.Entity("InternalSEO.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<long>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValueSql("SYSDATETIMEOFFSET()");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<long?>("LastLoginAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<long?>("LockoutEnd")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NormalizedEmail")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("TEXT");

                    b.Property<long?>("RefreshTokenExpiryTime")
                        .HasColumnType("INTEGER");

                    b.Property<long>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValueSql("SYSDATETIMEOFFSET()");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .IsUnique();

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("InternalSEO.Domain.Entities.UserRole", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("TEXT");

                    b.Property<long>("AssignedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValueSql("SYSDATETIMEOFFSET()");

                    b.Property<Guid?>("AssignedBy")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles", (string)null);
                });

            modelBuilder.Entity("InternalSEO.Domain.Entities.ActivityLog", b =>
                {
                    b.HasOne("InternalSEO.Domain.Entities.User", "Actor")
                        .WithMany("ActivityLogs")
                        .HasForeignKey("ActorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("InternalSEO.Domain.Entities.Project", "Project")
                        .WithMany("ActivityLogs")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Actor");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("InternalSEO.Domain.Entities.AuditIssue", b =>
                {
                    b.HasOne("InternalSEO.Domain.Entities.CrawlRun", "CrawlRun")
                        .WithMany("Issues")
                        .HasForeignKey("CrawlRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InternalSEO.Domain.Entities.Project", "Project")
                        .WithMany("AuditIssues")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("InternalSEO.Domain.Entities.AuditRule", "Rule")
                        .WithMany("Issues")
                        .HasForeignKey("RuleCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CrawlRun");

                    b.Navigation("Project");

                    b.Navigation("Rule");
                });

            modelBuilder.Entity("InternalSEO.Domain.Entities.CrawlPage", b =>
                {
                    b.HasOne("InternalSEO.Domain.Entities.CrawlRun", "CrawlRun")
                        .WithMany("Pages")
                        .HasForeignKey("CrawlRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InternalSEO.Domain.Entities.Project", "Project")
                        .WithMany("CrawlPages")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("CrawlRun");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("InternalSEO.Domain.Entities.CrawlRun", b =>
                {
                    b.HasOne("InternalSEO.Domain.Entities.User", "Creator")
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("InternalSEO.Domain.Entities.Project", "Project")
                        .WithMany("CrawlRuns")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Creator");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("InternalSEO.Domain.Entities.IssueEvidence", b =>
                {
                    b.HasOne("InternalSEO.Domain.Entities.AuditIssue", "Issue")
                        .WithMany("Evidence")
                        .HasForeignKey("IssueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Issue");
                });

            modelBuilder.Entity("InternalSEO.Domain.Entities.Keyword", b =>
                {
                    b.HasOne("InternalSEO.Domain.Entities.User", "Creator")
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("InternalSEO.Domain.Entities.KeywordGroup", "Group")
                        .WithMany("Keywords")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("InternalSEO.Domain.Entities.Project", "Project")
                        .WithMany("Keywords")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Creator");

                    b.Navigation("Group");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("InternalSEO.Domain.Entities.KeywordGroup", b =>
                {
                    b.HasOne("InternalSEO.Domain.Entities.Project", "Project")
                        .WithMany("KeywordGroups")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("InternalSEO.Domain.Entities.KeywordTag", b =>
                {
                    b.HasOne("InternalSEO.Domain.Entities.Keyword", "Keyword")
                        .WithMany("KeywordTags")
                        .HasForeignKey("KeywordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InternalSEO.Domain.Entities.Tag", "Tag")
                        .WithMany("KeywordTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Keyword");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("InternalSEO.Domain.Entities.Project", b =>
                {
                    b.HasOne("InternalSEO.Domain.Entities.User", "Creator")
                        .WithMany("CreatedProjects")
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Creator");
                });

            modelBuilder.Entity("InternalSEO.Domain.Entities.ProjectMember", b =>
                {
                    b.HasOne("InternalSEO.Domain.Entities.Project", "Project")
                        .WithMany("Members")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InternalSEO.Domain.Entities.User", "User")
                        .WithMany("ProjectMemberships")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");

                    b.Navigation("User");
                });

            modelBuilder.Entity("InternalSEO.Domain.Entities.ProjectSettings", b =>
                {
                    b.HasOne("InternalSEO.Domain.Entities.Project", "Project")
                        .WithOne("Settings")
                        .HasForeignKey("InternalSEO.Domain.Entities.ProjectSettings", "ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("InternalSEO.Domain.Entities.RankResult", b =>
                {
                    b.HasOne("InternalSEO.Domain.Entities.Keyword", "Keyword")
                        .WithMany("RankResults")
                        .HasForeignKey("KeywordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InternalSEO.Domain.Entities.Project", "Project")
                        .WithMany("RankResults")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Keyword");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("InternalSEO.Domain.Entities.Tag", b =>
                {
                    b.HasOne("InternalSEO.Domain.Entities.Project", "Project")
                        .WithMany("Tags")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("InternalSEO.Domain.Entities.UserRole", b =>
                {
                    b.HasOne("InternalSEO.Domain.Entities.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InternalSEO.Domain.Entities.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("InternalSEO.Domain.Entities.AuditIssue", b =>
                {
                    b.Navigation("Evidence");
                });

            modelBuilder.Entity("InternalSEO.Domain.Entities.AuditRule", b =>
                {
                    b.Navigation("Issues");
                });

            modelBuilder.Entity("InternalSEO.Domain.Entities.CrawlRun", b =>
                {
                    b.Navigation("Issues");

                    b.Navigation("Pages");
                });

            modelBuilder.Entity("InternalSEO.Domain.Entities.Keyword", b =>
                {
                    b.Navigation("KeywordTags");

                    b.Navigation("RankResults");
                });

            modelBuilder.Entity("InternalSEO.Domain.Entities.KeywordGroup", b =>
                {
                    b.Navigation("Keywords");
                });

            modelBuilder.Entity("InternalSEO.Domain.Entities.Project", b =>
                {
                    b.Navigation("ActivityLogs");

                    b.Navigation("AuditIssues");

                    b.Navigation("CrawlPages");

                    b.Navigation("CrawlRuns");

                    b.Navigation("KeywordGroups");

                    b.Navigation("Keywords");

                    b.Navigation("Members");

                    b.Navigation("RankResults");

                    b.Navigation("Settings");

                    b.Navigation("Tags");
                });

            modelBuilder.Entity("InternalSEO.Domain.Entities.Role", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("InternalSEO.Domain.Entities.Tag", b =>
                {
                    b.Navigation("KeywordTags");
                });

            modelBuilder.Entity("InternalSEO.Domain.Entities.User", b =>
                {
                    b.Navigation("ActivityLogs");

                    b.Navigation("CreatedProjects");

                    b.Navigation("ProjectMemberships");

                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
