export interface TimeSeriesPoint {
  date: string;
  referringDomains: number;
  backlinks: number;
  domainTrust: number;
  pageTrust: number;
  organicTraffic: number;
  newRefDomains: number;
  lostRefDomains: number;
  newBacklinks: number;
  lostBacklinks: number;
}

export interface AnchorData {
  id?: string;
  anchorText: string;
  backlinks: number;
  percent: number;
  referringDomains: number;
  dofollowCount?: number;
  dofollowPercent: number;
  firstSeen: string;
  lastSeen: string;
  wordCount?: number;
  sampleRefDomains?: { domain: string; dt: number; links: number }[];
  sampleBacklinks?: { sourceUrl: string; targetUrl: string; isDofollow: boolean }[];
}

export interface TrustDistributionData {
  range: string;
  refDomains: number;
  percent: number;
}

export interface CountryDistributionData {
  countryCode: string;
  countryName: string;
  flag: string;
  refDomains: number;
  percent: number;
}

export interface BacklinkRecord {
  id: string;
  sourceUrl: string;
  sourceTitle: string;
  targetUrl: string;
  anchorText: string;
  domainTraffic: string;
  domainTrafficNum: number;
  pageTraffic: string;
  pageTrafficNum: number;
  domainTrust: number;
  pageTrust: number;
  keywordsCount: number;
  firstSeen: string;
  lastSeen: string;
  status: "Active" | "New" | "Lost";
  linkType: "Text" | "Image" | "Redirect";
  isDofollow: boolean;
  isBestLink?: boolean;
}

export interface ReferringDomainRecord {
  id: string;
  domain: string;
  domainTrust: number;
  pageTrust?: number;
  domainTraffic: string;
  domainTrafficNum: number;
  linkTraffic?: string;
  linkTrafficNum?: number;
  backlinksCount: number;
  backlinkKeywords?: string;
  backlinkKeywordsNum?: number;
  keywords: string;
  keywordsNum: number;
  domainAge: string;
  firstSeen: string;
  lastSeen?: string;
  status: "Active" | "New" | "Lost";
  dofollowCount?: number;
  nofollowCount?: number;
  country?: string;
  countryCode?: string;
  flag?: string;
  ip?: string;
}

export interface PageRecord {
  id: string;
  url: string;
  backlinksCount: number;
  refDomainsCount: number;
  domainTrust: number;
  statusCode: number;
  title: string;
}

export interface IpRecord {
  id: string;
  ipAddress: string;
  subnet: string;
  country: string;
  countryCode: string;
  flag: string;
  refDomainsCount: number;
  backlinksCount: number;
}

export const MOCK_TIME_SERIES: TimeSeriesPoint[] = [
  {
    date: "28 Jun",
    referringDomains: 226,
    backlinks: 298,
    domainTrust: 42,
    pageTrust: 38,
    organicTraffic: 1420,
    newRefDomains: 3,
    lostRefDomains: 2,
    newBacklinks: 4,
    lostBacklinks: 3,
  },
  {
    date: "05 Jul",
    referringDomains: 224,
    backlinks: 294,
    domainTrust: 42,
    pageTrust: 38,
    organicTraffic: 1410,
    newRefDomains: 2,
    lostRefDomains: 4,
    newBacklinks: 3,
    lostBacklinks: 7,
  },
  {
    date: "12 Jul",
    referringDomains: 223,
    backlinks: 292,
    domainTrust: 42,
    pageTrust: 39,
    organicTraffic: 1450,
    newRefDomains: 8,
    lostRefDomains: 9,
    newBacklinks: 11,
    lostBacklinks: 13,
  },
  {
    date: "19 Jul",
    referringDomains: 222,
    backlinks: 290,
    domainTrust: 41,
    pageTrust: 38,
    organicTraffic: 1440,
    newRefDomains: 3,
    lostRefDomains: 4,
    newBacklinks: 5,
    lostBacklinks: 7,
  },
  {
    date: "26 Jul",
    referringDomains: 221,
    backlinks: 288,
    domainTrust: 41,
    pageTrust: 38,
    organicTraffic: 1435,
    newRefDomains: 4,
    lostRefDomains: 5,
    newBacklinks: 6,
    lostBacklinks: 8,
  },
  {
    date: "02 Aug",
    referringDomains: 219,
    backlinks: 286,
    domainTrust: 41,
    pageTrust: 37,
    organicTraffic: 1390,
    newRefDomains: 3,
    lostRefDomains: 5,
    newBacklinks: 4,
    lostBacklinks: 6,
  },
  {
    date: "09 Aug",
    referringDomains: 214,
    backlinks: 280,
    domainTrust: 40,
    pageTrust: 37,
    organicTraffic: 1360,
    newRefDomains: 2,
    lostRefDomains: 7,
    newBacklinks: 3,
    lostBacklinks: 9,
  },
  {
    date: "16 Aug",
    referringDomains: 198,
    backlinks: 263,
    domainTrust: 39,
    pageTrust: 36,
    organicTraffic: 1280,
    newRefDomains: 1,
    lostRefDomains: 17,
    newBacklinks: 2,
    lostBacklinks: 19,
  },
  {
    date: "23 Aug",
    referringDomains: 194,
    backlinks: 258,
    domainTrust: 39,
    pageTrust: 36,
    organicTraffic: 1290,
    newRefDomains: 3,
    lostRefDomains: 7,
    newBacklinks: 4,
    lostBacklinks: 9,
  },
  {
    date: "30 Aug",
    referringDomains: 191,
    backlinks: 256,
    domainTrust: 39,
    pageTrust: 35,
    organicTraffic: 1300,
    newRefDomains: 2,
    lostRefDomains: 5,
    newBacklinks: 3,
    lostBacklinks: 5,
  },
  {
    date: "06 Sep",
    referringDomains: 188,
    backlinks: 254,
    domainTrust: 38,
    pageTrust: 35,
    organicTraffic: 1270,
    newRefDomains: 2,
    lostRefDomains: 5,
    newBacklinks: 3,
    lostBacklinks: 5,
  },
  {
    date: "13 Sep",
    referringDomains: 186,
    backlinks: 252,
    domainTrust: 38,
    pageTrust: 35,
    organicTraffic: 1260,
    newRefDomains: 2,
    lostRefDomains: 4,
    newBacklinks: 3,
    lostBacklinks: 5,
  },
  {
    date: "20 Sep",
    referringDomains: 185,
    backlinks: 251,
    domainTrust: 38,
    pageTrust: 35,
    organicTraffic: 1265,
    newRefDomains: 3,
    lostRefDomains: 4,
    newBacklinks: 4,
    lostBacklinks: 5,
  },
  {
    date: "23 Sep",
    referringDomains: 184,
    backlinks: 250,
    domainTrust: 38,
    pageTrust: 35,
    organicTraffic: 1260,
    newRefDomains: 1,
    lostRefDomains: 2,
    newBacklinks: 2,
    lostBacklinks: 3,
  },
];

export const MOCK_TOP_ANCHORS: AnchorData[] = [
  {
    anchorText: "workcomposer.com",
    backlinks: 106,
    percent: 47.3,
    referringDomains: 72,
    dofollowPercent: 88,
    firstSeen: "14 Jan 2024",
    lastSeen: "23 Sep 2026",
  },
  {
    anchorText: "WorkComposer",
    backlinks: 30,
    percent: 13.4,
    referringDomains: 24,
    dofollowPercent: 92,
    firstSeen: "20 Feb 2024",
    lastSeen: "22 Sep 2026",
  },
  {
    anchorText: "No text",
    backlinks: 27,
    percent: 12.1,
    referringDomains: 19,
    dofollowPercent: 74,
    firstSeen: "05 Mar 2024",
    lastSeen: "20 Sep 2026",
  },
  {
    anchorText: "time tracking app",
    backlinks: 12,
    percent: 5.4,
    referringDomains: 11,
    dofollowPercent: 95,
    firstSeen: "12 May 2024",
    lastSeen: "21 Sep 2026",
  },
  {
    anchorText: "claims",
    backlinks: 10,
    percent: 4.5,
    referringDomains: 8,
    dofollowPercent: 60,
    firstSeen: "18 Jun 2024",
    lastSeen: "19 Sep 2026",
  },
  {
    anchorText: "https://www.workco...",
    backlinks: 10,
    percent: 4.5,
    referringDomains: 7,
    dofollowPercent: 80,
    firstSeen: "01 Jul 2024",
    lastSeen: "22 Sep 2026",
  },
  {
    anchorText: "time tracking with sc...",
    backlinks: 8,
    percent: 3.6,
    referringDomains: 6,
    dofollowPercent: 100,
    firstSeen: "15 Jul 2024",
    lastSeen: "18 Sep 2026",
  },
  {
    anchorText: "Visit website",
    backlinks: 8,
    percent: 3.6,
    referringDomains: 8,
    dofollowPercent: 75,
    firstSeen: "28 Jul 2024",
    lastSeen: "17 Sep 2026",
  },
  {
    anchorText: "employee monitorin...",
    backlinks: 8,
    percent: 3.6,
    referringDomains: 7,
    dofollowPercent: 90,
    firstSeen: "04 Aug 2024",
    lastSeen: "23 Sep 2026",
  },
  {
    anchorText: "View Product",
    backlinks: 5,
    percent: 2.2,
    referringDomains: 5,
    dofollowPercent: 100,
    firstSeen: "12 Aug 2024",
    lastSeen: "21 Sep 2026",
  },
];

export const MOCK_WORKCOMPOSER_ANCHORS: AnchorData[] = [
  { id: "wc-1", anchorText: "workcomposer.com", referringDomains: 96, backlinks: 106, percent: 5.7, dofollowCount: 6, dofollowPercent: 5.7, firstSeen: "18 Jan 2025", lastSeen: "07 Sep 2026", wordCount: 1 },
  { id: "wc-2", anchorText: "WorkComposer", referringDomains: 28, backlinks: 30, percent: 23.6, dofollowCount: 25, dofollowPercent: 23.6, firstSeen: "18 Nov 2022", lastSeen: "23 Sep 2026", wordCount: 1 },
  { id: "wc-3", anchorText: "claims", referringDomains: 10, backlinks: 10, percent: 9.4, dofollowCount: 10, dofollowPercent: 9.4, firstSeen: "09 Aug 2025", lastSeen: "24 Sep 2026", wordCount: 1 },
  { id: "wc-4", anchorText: "Visit Website", referringDomains: 7, backlinks: 9, percent: 3.8, dofollowCount: 4, dofollowPercent: 3.8, firstSeen: "29 Sep 2025", lastSeen: "25 Sep 2026", wordCount: 2 },
  { id: "wc-5", anchorText: "employee monitoring ...", referringDomains: 5, backlinks: 8, percent: 7.5, dofollowCount: 8, dofollowPercent: 7.5, firstSeen: "19 Nov 2022", lastSeen: "20 Jul 2026", wordCount: 3 },
  { id: "wc-6", anchorText: "No text", referringDomains: 4, backlinks: 27, percent: 1.9, dofollowCount: 2, dofollowPercent: 1.9, firstSeen: "03 Mar 2024", lastSeen: "23 Jun 2026", wordCount: 2 },
  { id: "wc-7", anchorText: "compañía WorkComp...", referringDomains: 4, backlinks: 4, percent: 3.8, dofollowCount: 4, dofollowPercent: 3.8, firstSeen: "12 Jul 2025", lastSeen: "07 Sep 2026", wordCount: 2 },
  { id: "wc-8", anchorText: "time tracking with scr...", referringDomains: 4, backlinks: 8, percent: 7.5, dofollowCount: 8, dofollowPercent: 7.5, firstSeen: "30 May 2025", lastSeen: "20 Jul 2026", wordCount: 4 },
  { id: "wc-9", anchorText: "time tracking app", referringDomains: 4, backlinks: 5, percent: 88.0, dofollowCount: 5, dofollowPercent: 88.0, firstSeen: "22 Apr 2024", lastSeen: "23 Sep 2026", wordCount: 3 },
  { id: "wc-10", anchorText: "remote work tracker", referringDomains: 3, backlinks: 5, percent: 4.1, dofollowCount: 4, dofollowPercent: 80.0, firstSeen: "05 Aug 2024", lastSeen: "17 Sep 2026", wordCount: 3 },
  { id: "wc-11", anchorText: "workcomposer", referringDomains: 3, backlinks: 4, percent: 3.3, dofollowCount: 3, dofollowPercent: 75.0, firstSeen: "19 Aug 2024", lastSeen: "16 Sep 2026", wordCount: 1 },
  { id: "wc-12", anchorText: "best employee tracking software", referringDomains: 3, backlinks: 4, percent: 3.3, dofollowCount: 4, dofollowPercent: 100.0, firstSeen: "01 Sep 2024", lastSeen: "15 Sep 2026", wordCount: 4 },
  { id: "wc-13", anchorText: "website", referringDomains: 2, backlinks: 3, percent: 2.5, dofollowCount: 2, dofollowPercent: 66.7, firstSeen: "12 Sep 2024", lastSeen: "14 Sep 2026", wordCount: 1 },
  { id: "wc-14", anchorText: "source", referringDomains: 2, backlinks: 3, percent: 2.5, dofollowCount: 1, dofollowPercent: 50.0, firstSeen: "25 Sep 2024", lastSeen: "13 Sep 2026", wordCount: 1 },
  { id: "wc-15", anchorText: "learn more", referringDomains: 2, backlinks: 3, percent: 2.5, dofollowCount: 3, dofollowPercent: 100.0, firstSeen: "08 Oct 2024", lastSeen: "12 Sep 2026", wordCount: 2 },
  { id: "wc-16", anchorText: "https://www.workcomposer.com", referringDomains: 2, backlinks: 2, percent: 1.7, dofollowCount: 1, dofollowPercent: 50.0, firstSeen: "20 Oct 2024", lastSeen: "11 Sep 2026", wordCount: 1 },
  { id: "wc-17", anchorText: "WorkComposer features", referringDomains: 2, backlinks: 2, percent: 1.7, dofollowCount: 2, dofollowPercent: 100.0, firstSeen: "04 Nov 2024", lastSeen: "10 Sep 2026", wordCount: 2 },
  { id: "wc-18", anchorText: "automatic time tracking", referringDomains: 2, backlinks: 2, percent: 1.7, dofollowCount: 2, dofollowPercent: 100.0, firstSeen: "18 Nov 2024", lastSeen: "09 Sep 2026", wordCount: 3 },
  { id: "wc-19", anchorText: "screen monitoring app", referringDomains: 2, backlinks: 2, percent: 1.7, dofollowCount: 2, dofollowPercent: 100.0, firstSeen: "01 Dec 2024", lastSeen: "08 Sep 2026", wordCount: 3 },
  { id: "wc-20", anchorText: "WorkComposer pricing", referringDomains: 2, backlinks: 2, percent: 1.7, dofollowCount: 2, dofollowPercent: 100.0, firstSeen: "15 Dec 2024", lastSeen: "07 Sep 2026", wordCount: 2 },
  { id: "wc-21", anchorText: "freelancer time tracker", referringDomains: 1, backlinks: 2, percent: 1.7, dofollowCount: 1, dofollowPercent: 50.0, firstSeen: "03 Jan 2025", lastSeen: "06 Sep 2026", wordCount: 3 },
  { id: "wc-22", anchorText: "download WorkComposer", referringDomains: 1, backlinks: 2, percent: 1.7, dofollowCount: 2, dofollowPercent: 100.0, firstSeen: "17 Jan 2025", lastSeen: "05 Sep 2026", wordCount: 2 },
  { id: "wc-23", anchorText: "team productivity software", referringDomains: 1, backlinks: 1, percent: 0.8, dofollowCount: 1, dofollowPercent: 100.0, firstSeen: "30 Jan 2025", lastSeen: "04 Sep 2026", wordCount: 3 },
  { id: "wc-24", anchorText: "click here", referringDomains: 1, backlinks: 1, percent: 0.8, dofollowCount: 0, dofollowPercent: 0.0, firstSeen: "14 Feb 2025", lastSeen: "03 Sep 2026", wordCount: 2 },
  { id: "wc-25", anchorText: "work composer tool", referringDomains: 1, backlinks: 1, percent: 0.8, dofollowCount: 1, dofollowPercent: 100.0, firstSeen: "28 Feb 2025", lastSeen: "02 Sep 2026", wordCount: 3 },
  { id: "wc-26", anchorText: "activity monitoring", referringDomains: 1, backlinks: 1, percent: 0.8, dofollowCount: 1, dofollowPercent: 100.0, firstSeen: "15 Mar 2025", lastSeen: "01 Sep 2026", wordCount: 2 },
  { id: "wc-27", anchorText: "attendance tracker", referringDomains: 1, backlinks: 1, percent: 0.8, dofollowCount: 1, dofollowPercent: 100.0, firstSeen: "29 Mar 2025", lastSeen: "31 Aug 2026", wordCount: 2 },
  { id: "wc-28", anchorText: "project time tracking", referringDomains: 1, backlinks: 1, percent: 0.8, dofollowCount: 1, dofollowPercent: 100.0, firstSeen: "12 Apr 2025", lastSeen: "30 Aug 2026", wordCount: 3 },
  { id: "wc-29", anchorText: "desktop tracker", referringDomains: 1, backlinks: 1, percent: 0.8, dofollowCount: 1, dofollowPercent: 100.0, firstSeen: "26 Apr 2025", lastSeen: "29 Aug 2026", wordCount: 2 },
  { id: "wc-30", anchorText: "time billing software", referringDomains: 1, backlinks: 1, percent: 0.8, dofollowCount: 1, dofollowPercent: 100.0, firstSeen: "10 May 2025", lastSeen: "28 Aug 2026", wordCount: 3 },
  { id: "wc-31", anchorText: "stealth employee monitor", referringDomains: 1, backlinks: 1, percent: 0.8, dofollowCount: 1, dofollowPercent: 100.0, firstSeen: "24 May 2025", lastSeen: "27 Aug 2026", wordCount: 3 },
  { id: "wc-32", anchorText: "work hours tracker", referringDomains: 1, backlinks: 1, percent: 0.8, dofollowCount: 1, dofollowPercent: 100.0, firstSeen: "07 Jun 2025", lastSeen: "26 Aug 2026", wordCount: 3 },
  { id: "wc-33", anchorText: "workcomposer app", referringDomains: 1, backlinks: 1, percent: 0.8, dofollowCount: 1, dofollowPercent: 100.0, firstSeen: "21 Jun 2025", lastSeen: "25 Aug 2026", wordCount: 2 },
  { id: "wc-34", anchorText: "time log tool", referringDomains: 1, backlinks: 1, percent: 0.8, dofollowCount: 1, dofollowPercent: 100.0, firstSeen: "05 Jul 2025", lastSeen: "24 Aug 2026", wordCount: 3 },
];

export const MOCK_ZOHO_ANCHORS: AnchorData[] = [
  {
    id: "zoho-1",
    anchorText: "workco.com",
    referringDomains: 26,
    backlinks: 33,
    dofollowCount: 10,
    dofollowPercent: 45.5,
    percent: 45.5,
    firstSeen: "09 Mar 2024",
    lastSeen: "12 Sep 2026",
    wordCount: 1,
    sampleRefDomains: [
      { domain: "techcrunch.com", dt: 92, links: 8 },
      { domain: "g2.com", dt: 88, links: 12 },
      { domain: "capterra.com", dt: 86, links: 6 },
      { domain: "trustradius.com", dt: 81, links: 4 },
      { domain: "softwareadvice.com", dt: 79, links: 3 },
    ],
    sampleBacklinks: [
      { sourceUrl: "https://techcrunch.com/2024/03/09/social-media-management-tools/", targetUrl: "https://workco.com", isDofollow: true },
      { sourceUrl: "https://www.g2.com/products/zoho-social/reviews", targetUrl: "https://workco.com", isDofollow: true },
      { sourceUrl: "https://www.capterra.com/p/142981/Zoho-Social/", targetUrl: "https://workco.com", isDofollow: true },
      { sourceUrl: "https://www.trustradius.com/products/zoho-social/reviews", targetUrl: "https://workco.com", isDofollow: false },
    ],
  },
  {
    id: "zoho-2",
    anchorText: "WorkCo Digital",
    referringDomains: 7,
    backlinks: 8,
    dofollowCount: 4,
    dofollowPercent: 18.2,
    percent: 18.2,
    firstSeen: "17 Jun 2025",
    lastSeen: "23 Sep 2026",
    wordCount: 2,
    sampleRefDomains: [
      { domain: "forbes.com", dt: 94, links: 2 },
      { domain: "hubspot.com", dt: 93, links: 2 },
      { domain: "buffer.com", dt: 84, links: 2 },
      { domain: "zapier.com", dt: 89, links: 1 },
      { domain: "socialpilot.co", dt: 76, links: 1 },
    ],
    sampleBacklinks: [
      { sourceUrl: "https://forbes.com/advisor/business/software/best-social-media-management-software/", targetUrl: "https://workco.com", isDofollow: true },
      { sourceUrl: "https://blog.hubspot.com/marketing/social-media-management-tools", targetUrl: "https://workco.com", isDofollow: true },
    ],
  },
  {
    id: "zoho-3",
    anchorText: "http://workco.com",
    referringDomains: 3,
    backlinks: 7,
    dofollowCount: 6,
    dofollowPercent: 27.3,
    percent: 27.3,
    firstSeen: "01 Oct 2024",
    lastSeen: "17 Aug 2026",
    wordCount: 1,
    sampleRefDomains: [
      { domain: "medium.com", dt: 95, links: 4 },
      { domain: "quora.com", dt: 91, links: 2 },
      { domain: "producthunt.com", dt: 87, links: 1 },
    ],
    sampleBacklinks: [
      { sourceUrl: "https://medium.com/@marketingguru/top-marketing-stacks-2024", targetUrl: "http://workco.com", isDofollow: true },
      { sourceUrl: "https://www.quora.com/What-is-the-best-social-media-management-tool", targetUrl: "http://workco.com", isDofollow: true },
    ],
  },
  {
    id: "zoho-4",
    anchorText: "Probar gratis",
    referringDomains: 1,
    backlinks: 3,
    dofollowCount: 0,
    dofollowPercent: 0,
    percent: 0,
    firstSeen: "01 Sep 2025",
    lastSeen: "09 Sep 2026",
    wordCount: 2,
    sampleRefDomains: [
      { domain: "marketingdirecto.com", dt: 68, links: 3 },
    ],
    sampleBacklinks: [
      { sourceUrl: "https://www.marketingdirecto.com/digital-general/herramientas-redes-sociales", targetUrl: "https://workco.com/es/pricing", isDofollow: false },
    ],
  },
  {
    id: "zoho-5",
    anchorText: "Probar WorkCo Digital gratis",
    referringDomains: 1,
    backlinks: 1,
    dofollowCount: 0,
    dofollowPercent: 0,
    percent: 0,
    firstSeen: "01 Sep 2025",
    lastSeen: "09 Sep 2026",
    wordCount: 4,
    sampleRefDomains: [
      { domain: "marketingdirecto.com", dt: 68, links: 1 },
    ],
    sampleBacklinks: [
      { sourceUrl: "https://www.marketingdirecto.com/digital-general/guia-zoho-social-2025", targetUrl: "https://workco.com/es/signup", isDofollow: false },
    ],
  },
  {
    id: "zoho-6",
    anchorText: "https://www.workco.com",
    referringDomains: 1,
    backlinks: 1,
    dofollowCount: 0,
    dofollowPercent: 0,
    percent: 0,
    firstSeen: "17 Jan 2026",
    lastSeen: "07 Sep 2026",
    wordCount: 1,
    sampleRefDomains: [
      { domain: "dev.to", dt: 82, links: 1 },
    ],
    sampleBacklinks: [
      { sourceUrl: "https://dev.to/community/social-scheduler-api-breakdown", targetUrl: "https://www.workco.com", isDofollow: false },
    ],
  },
  {
    id: "zoho-7",
    anchorText: "No text",
    referringDomains: 1,
    backlinks: 2,
    dofollowCount: 2,
    dofollowPercent: 9.1,
    percent: 9.1,
    firstSeen: "12 Dec 2025",
    lastSeen: "11 Sep 2025",
    wordCount: 2,
    sampleRefDomains: [
      { domain: "dribbble.com", dt: 89, links: 2 },
    ],
    sampleBacklinks: [
      { sourceUrl: "https://dribbble.com/shots/zoho-social-dashboard-concept", targetUrl: "https://workco.com", isDofollow: true },
    ],
  },
  {
    id: "zoho-8",
    anchorText: "Tool #5: WorkCo Digital",
    referringDomains: 1,
    backlinks: 1,
    dofollowCount: 1,
    dofollowPercent: 4.5,
    percent: 4.5,
    firstSeen: "07 Dec 2025",
    lastSeen: "08 Jun 2026",
    wordCount: 4,
    sampleRefDomains: [
      { domain: "searchenginejournal.com", dt: 89, links: 1 },
    ],
    sampleBacklinks: [
      { sourceUrl: "https://www.searchenginejournal.com/top-social-management-platforms/492011/", targetUrl: "https://workco.com", isDofollow: true },
    ],
  },
  {
    id: "zoho-9",
    anchorText: "WorkCo",
    referringDomains: 1,
    backlinks: 7,
    dofollowCount: 0,
    dofollowPercent: 0,
    percent: 0,
    firstSeen: "21 Aug 2025",
    lastSeen: "13 Sep 2026",
    wordCount: 1,
    sampleRefDomains: [
      { domain: "reddit.com", dt: 96, links: 7 },
    ],
    sampleBacklinks: [
      { sourceUrl: "https://www.reddit.com/r/socialmedia/comments/zoho_social_review/", targetUrl: "https://workco.com", isDofollow: false },
    ],
  },
  {
    id: "zoho-10",
    anchorText: "ZohoСоциальные",
    referringDomains: 1,
    backlinks: 1,
    dofollowCount: 0,
    dofollowPercent: 0,
    percent: 0,
    firstSeen: "13 Sep 2025",
    lastSeen: "20 Nov 2025",
    wordCount: 1,
    sampleRefDomains: [
      { domain: "habr.com", dt: 84, links: 1 },
    ],
    sampleBacklinks: [
      { sourceUrl: "https://habr.com/ru/articles/691238/", targetUrl: "https://workco.com", isDofollow: false },
    ],
  },
  {
    id: "zoho-11",
    anchorText: "ZohoSocisal",
    referringDomains: 1,
    backlinks: 1,
    dofollowCount: 0,
    dofollowPercent: 0,
    percent: 0,
    firstSeen: "04 Sep 2025",
    lastSeen: "12 Nov 2025",
    wordCount: 1,
    sampleRefDomains: [
      { domain: "wordpress.org", dt: 97, links: 1 },
    ],
    sampleBacklinks: [
      { sourceUrl: "https://wordpress.org/support/topic/zoho-social-integration-typo/", targetUrl: "https://workco.com", isDofollow: false },
    ],
  },
];

export const MOCK_DOMAIN_TRUST_DISTRIBUTION: TrustDistributionData[] = [
  { range: "0-9", refDomains: 35, percent: 19.44 },
  { range: "10-19", refDomains: 20, percent: 11.11 },
  { range: "20-29", refDomains: 19, percent: 10.56 },
  { range: "30-39", refDomains: 19, percent: 10.56 },
  { range: "40-49", refDomains: 12, percent: 6.67 },
  { range: "50-59", refDomains: 23, percent: 12.78 },
  { range: "60-69", refDomains: 20, percent: 11.11 },
  { range: "70-79", refDomains: 13, percent: 7.22 },
  { range: "80-89", refDomains: 11, percent: 6.11 },
  { range: "90-100", refDomains: 8, percent: 4.44 },
];

export const MOCK_COUNTRY_DISTRIBUTION: CountryDistributionData[] = [
  { countryCode: "sg", countryName: "Singapore", flag: "🇸🇬", refDomains: 46, percent: 38.7 },
  { countryCode: "us", countryName: "USA", flag: "🇺🇸", refDomains: 34, percent: 28.6 },
  { countryCode: "md", countryName: "Moldova", flag: "🇲🇩", refDomains: 16, percent: 13.4 },
  { countryCode: "at", countryName: "Austria", flag: "🇦🇹", refDomains: 8, percent: 6.7 },
  { countryCode: "de", countryName: "Germany", flag: "🇩🇪", refDomains: 5, percent: 4.2 },
  { countryCode: "ro", countryName: "Romania", flag: "🇷🇴", refDomains: 4, percent: 3.4 },
  { countryCode: "ch", countryName: "Switzerland", flag: "🇨🇭", refDomains: 2, percent: 1.7 },
  { countryCode: "fr", countryName: "France", flag: "🇫🇷", refDomains: 2, percent: 1.7 },
  { countryCode: "gb", countryName: "United Kingdom", flag: "🇬🇧", refDomains: 1, percent: 0.8 },
  { countryCode: "vn", countryName: "Vietnam", flag: "🇻🇳", refDomains: 1, percent: 0.8 },
];

const BASE_MOCK_BACKLINKS: BacklinkRecord[] = [
  {
    id: "bl-1",
    sourceTitle: "Samsung admits to security wormhole in some Galaxy devices • The Register",
    sourceUrl: "https://www.theregister.com/2025/04/28/security_news_in_brief/",
    targetUrl: "https://www.workcomposer.com/features/auto-screenshots/",
    anchorText: "scheduled screenshot capture",
    domainTraffic: "69.8K",
    domainTrafficNum: 69800,
    pageTraffic: "0",
    pageTrafficNum: 0,
    domainTrust: 93,
    pageTrust: 27,
    keywordsCount: 19,
    firstSeen: "19 Jul 2025",
    lastSeen: "02 Feb 2026",
    status: "Active",
    linkType: "Text",
    isDofollow: false,
    isBestLink: false,
  },
  {
    id: "bl-2",
    sourceTitle: "The 10 Best Apps You Can Use to Reduce Overtime Work",
    sourceUrl: "https://www.makeuseof.com/best-apps-to-reduce-overtime-work/",
    targetUrl: "https://www.workcomposer.com/",
    anchorText: "WorkComposer",
    domainTraffic: "1.2M",
    domainTrafficNum: 1200000,
    pageTraffic: "0",
    pageTrafficNum: 0,
    domainTrust: 91,
    pageTrust: 23,
    keywordsCount: 5,
    firstSeen: "08 Dec 2025",
    lastSeen: "05 May 2026",
    status: "Active",
    linkType: "Text",
    isDofollow: true,
    isBestLink: true,
  },
  {
    id: "bl-3",
    sourceTitle: "Las empresas querían monitorizar el teletrabajo con capturas: ahora tienen un grave problema de seguridad y fuga de datos",
    sourceUrl: "https://www.xataka.com/seguridad/empresas-querian-monitorizar-teletrabajo-capturas-ahora-tienen-grave-problema-seguridad-fuga-datos",
    targetUrl: "https://www.workcomposer.com/",
    anchorText: "compañía WorkComposer",
    domainTraffic: "7.4M",
    domainTrafficNum: 7400000,
    pageTraffic: "0",
    pageTrafficNum: 0,
    domainTrust: 89,
    pageTrust: 22,
    keywordsCount: 10,
    firstSeen: "12 Jul 2025",
    lastSeen: "20 Dec 2025",
    status: "Active",
    linkType: "Text",
    isDofollow: true,
    isBestLink: true,
  },
  {
    id: "bl-4",
    sourceTitle: "Brand Identity Company - Brand Identity Guru - King Ranks",
    sourceUrl: "https://kingranks.com/brand-identity-company-brand-identity-guru/",
    targetUrl: "https://workcomposer.com/",
    anchorText: "WorkComposer",
    domainTraffic: "0",
    domainTrafficNum: 0,
    pageTraffic: "0",
    pageTrafficNum: 0,
    domainTrust: 74,
    pageTrust: 18,
    keywordsCount: 0,
    firstSeen: "18 Nov 2022",
    lastSeen: "13 Dec 2025",
    status: "Active",
    linkType: "Text",
    isDofollow: true,
    isBestLink: false,
  },
  {
    id: "bl-5",
    sourceTitle: "Smart Book Marketing Helps Your Career As An Author | Web Rank Site",
    sourceUrl: "https://webranksite.com/smart-book-marketing-helps-your-career-as-an-author/",
    targetUrl: "https://workcomposer.com/",
    anchorText: "WorkComposer",
    domainTraffic: "0",
    domainTrafficNum: 0,
    pageTraffic: "0",
    pageTrafficNum: 0,
    domainTrust: 71,
    pageTrust: 15,
    keywordsCount: 0,
    firstSeen: "16 Aug 2025",
    lastSeen: "04 Nov 2025",
    status: "Active",
    linkType: "Text",
    isDofollow: true,
    isBestLink: false,
  },
  {
    id: "bl-6",
    sourceTitle: "25 melhores ferramentas para gerenciamento de tempo | AppTuts",
    sourceUrl: "https://www.apptuts.net/tutorial/android/ferramentas-gerenciamento-tempo/",
    targetUrl: "https://www.workcomposer.com/",
    anchorText: "acesse o site oficial",
    domainTraffic: "657",
    domainTrafficNum: 657,
    pageTraffic: "0",
    pageTrafficNum: 0,
    domainTrust: 73,
    pageTrust: 12,
    keywordsCount: 6,
    firstSeen: "13 Jun 2025",
    lastSeen: "19 Aug 2026",
    status: "Active",
    linkType: "Text",
    isDofollow: false,
    isBestLink: false,
  },
  {
    id: "bl-7",
    sourceTitle: "How to Use Instagram Reels for Digitals Marketings | 99 Best Site",
    sourceUrl: "https://99bestsite.com/how-to-use-instagram-reels-for-digitals-marketings/",
    targetUrl: "https://workcomposer.com/",
    anchorText: "WorkComposer",
    domainTraffic: "0",
    domainTrafficNum: 0,
    pageTraffic: "0",
    pageTrafficNum: 0,
    domainTrust: 49,
    pageTrust: 10,
    keywordsCount: 0,
    firstSeen: "05 Jul 2025",
    lastSeen: "16 Aug 2025",
    status: "Active",
    linkType: "Text",
    isDofollow: true,
    isBestLink: false,
  },
  {
    id: "bl-8",
    sourceTitle: "How to Use Instagram Reels for Digitals Marketings | Top Link Sites",
    sourceUrl: "https://toplinksites.com/how-to-use-instagram-reels-for-digitals-marketings/",
    targetUrl: "https://workcomposer.com/",
    anchorText: "WorkComposer",
    domainTraffic: "0",
    domainTrafficNum: 0,
    pageTraffic: "0",
    pageTrafficNum: 0,
    domainTrust: 45,
    pageTrust: 8,
    keywordsCount: 0,
    firstSeen: "10 Oct 2025",
    lastSeen: "10 Oct 2025",
    status: "Active",
    linkType: "Text",
    isDofollow: true,
    isBestLink: false,
  },
  {
    id: "bl-9",
    sourceTitle: "How to Use Instagram Reels for Digitals Marketings | Pre Post Link",
    sourceUrl: "https://prepostlink.com/how-to-use-instagram-reels-for-digitals-marketings/",
    targetUrl: "https://workcomposer.com/",
    anchorText: "WorkComposer",
    domainTraffic: "0",
    domainTrafficNum: 0,
    pageTraffic: "0",
    pageTrafficNum: 0,
    domainTrust: 45,
    pageTrust: 8,
    keywordsCount: 0,
    firstSeen: "16 Aug 2025",
    lastSeen: "16 Aug 2025",
    status: "Active",
    linkType: "Text",
    isDofollow: true,
    isBestLink: false,
  },
  {
    id: "bl-10",
    sourceTitle: "How to Use Instagram Reels for Digitals Marketings | Best Directory Site",
    sourceUrl: "https://bestdirectorysite.com/how-to-use-instagram-reels-for-digitals-marketings/",
    targetUrl: "https://workcomposer.com/",
    anchorText: "WorkComposer",
    domainTraffic: "0",
    domainTrafficNum: 0,
    pageTraffic: "0",
    pageTrafficNum: 0,
    domainTrust: 46,
    pageTrust: 8,
    keywordsCount: 0,
    firstSeen: "15 Aug 2025",
    lastSeen: "12 Oct 2025",
    status: "Active",
    linkType: "Text",
    isDofollow: true,
    isBestLink: false,
  },
  {
    id: "bl-11",
    sourceTitle: "How to Use Instagram Reels for Digitals Marketings | Virtuals Directory",
    sourceUrl: "https://virtualsdirectory.com/how-to-use-instagram-reels-for-digitals-marketings/",
    targetUrl: "https://workcomposer.com/",
    anchorText: "WorkComposer",
    domainTraffic: "0",
    domainTrafficNum: 0,
    pageTraffic: "0",
    pageTrafficNum: 0,
    domainTrust: 45,
    pageTrust: 8,
    keywordsCount: 0,
    firstSeen: "27 Jun 2025",
    lastSeen: "16 Aug 2025",
    status: "Active",
    linkType: "Text",
    isDofollow: true,
    isBestLink: false,
  },
  {
    id: "bl-12",
    sourceTitle: "WorkComposer Alternatives & Competitors - SaaS Hub",
    sourceUrl: "https://www.saashub.com/workcomposer-alternatives",
    targetUrl: "https://www.workcomposer.com/pricing/",
    anchorText: "Official Pricing",
    domainTraffic: "206.6K",
    domainTrafficNum: 206600,
    pageTraffic: "0",
    pageTrafficNum: 0,
    domainTrust: 87,
    pageTrust: 0,
    keywordsCount: 0,
    firstSeen: "07 Sep 2026",
    lastSeen: "07 Sep 2026",
    status: "Active",
    linkType: "Text",
    isDofollow: false,
    isBestLink: false,
  },
  {
    id: "bl-13",
    sourceTitle: "WorkComposer Down? WorkComposer status and issues.",
    sourceUrl: "https://www.saashub.com/workcomposer-status",
    targetUrl: "https://www.workcomposer.com/",
    anchorText: "workcomposer.com",
    domainTraffic: "206.6K",
    domainTrafficNum: 206600,
    pageTraffic: "0",
    pageTrafficNum: 0,
    domainTrust: 87,
    pageTrust: 0,
    keywordsCount: 0,
    firstSeen: "07 Sep 2026",
    lastSeen: "07 Sep 2026",
    status: "Active",
    linkType: "Text",
    isDofollow: false,
    isBestLink: false,
  },
  {
    id: "bl-14",
    sourceTitle: "WorkComposer Alternatives & Competitors - SaaS Hub",
    sourceUrl: "https://www.saashub.com/workcomposer-alternatives",
    targetUrl: "https://www.workcomposer.com/",
    anchorText: "Visit website",
    domainTraffic: "206.6K",
    domainTrafficNum: 206600,
    pageTraffic: "0",
    pageTrafficNum: 0,
    domainTrust: 87,
    pageTrust: 0,
    keywordsCount: 0,
    firstSeen: "07 Sep 2026",
    lastSeen: "07 Sep 2026",
    status: "Active",
    linkType: "Text",
    isDofollow: true,
    isBestLink: true,
  },
  {
    id: "bl-15",
    sourceTitle: "Free Time Tracking Software - Demostar",
    sourceUrl: "https://demostar.win/products/free-time-tracking-software",
    targetUrl: "https://workcomposer.com/",
    anchorText: "Visit website",
    domainTraffic: "19",
    domainTrafficNum: 19,
    pageTraffic: "0",
    pageTrafficNum: 0,
    domainTrust: 1,
    pageTrust: 0,
    keywordsCount: 0,
    firstSeen: "31 Aug 2026",
    lastSeen: "31 Aug 2026",
    status: "Active",
    linkType: "Text",
    isDofollow: true,
    isBestLink: false,
  },
  {
    id: "bl-16",
    sourceTitle: "15 Best Productivity & Time Tracking Tools for Remote Teams",
    sourceUrl: "https://techreviewdaily.io/productivity/top-remote-team-tools-2026",
    targetUrl: "https://www.workcomposer.com/",
    anchorText: "workcomposer.com",
    domainTraffic: "68.2K",
    domainTrafficNum: 68200,
    pageTraffic: "0",
    pageTrafficNum: 0,
    domainTrust: 68,
    pageTrust: 52,
    keywordsCount: 14,
    firstSeen: "14 Jan 2024",
    lastSeen: "23 Sep 2026",
    status: "Active",
    linkType: "Text",
    isDofollow: true,
    isBestLink: true,
  },
  {
    id: "bl-17",
    sourceTitle: "WorkComposer Software Reviews, Pricing & Ratings",
    sourceUrl: "https://hub.saasdirectory.com/listing/workcomposer-app",
    targetUrl: "https://www.workcomposer.com/",
    anchorText: "WorkComposer",
    domainTraffic: "145.4K",
    domainTrafficNum: 145400,
    pageTraffic: "0",
    pageTrafficNum: 0,
    domainTrust: 74,
    pageTrust: 61,
    keywordsCount: 22,
    firstSeen: "20 Feb 2024",
    lastSeen: "22 Sep 2026",
    status: "Active",
    linkType: "Text",
    isDofollow: true,
    isBestLink: false,
  },
  {
    id: "bl-18",
    sourceTitle: "The Complete Guide to Time Tracking & Employee Monitoring",
    sourceUrl: "https://remoteworkersguide.org/best-time-tracking-software",
    targetUrl: "https://www.workcomposer.com/features/work-time-tracking/",
    anchorText: "time tracking app",
    domainTraffic: "32.1K",
    domainTrafficNum: 32100,
    pageTraffic: "0",
    pageTrafficNum: 0,
    domainTrust: 58,
    pageTrust: 44,
    keywordsCount: 8,
    firstSeen: "12 May 2024",
    lastSeen: "21 Sep 2026",
    status: "Active",
    linkType: "Text",
    isDofollow: true,
    isBestLink: false,
  },
  {
    id: "bl-19",
    sourceTitle: "Automatic Screenshot Capture Tools for Freelancers",
    sourceUrl: "https://digitalnomadsdigest.co/screenshot-monitoring-apps/",
    targetUrl: "https://www.workcomposer.com/wc/time-and-screenshot-tracking-software/",
    anchorText: "time tracking with screen capture",
    domainTraffic: "18.5K",
    domainTrafficNum: 18500,
    pageTrust: 41,
    domainTrust: 52,
    pageTraffic: "0",
    pageTrafficNum: 0,
    keywordsCount: 4,
    firstSeen: "15 Jul 2024",
    lastSeen: "18 Sep 2026",
    status: "Active",
    linkType: "Text",
    isDofollow: true,
    isBestLink: false,
  },
  {
    id: "bl-20",
    sourceTitle: "Modern Tech Stack Tools for Scaling Agencies",
    sourceUrl: "https://startupstack.tools/category/time-management",
    targetUrl: "https://www.workcomposer.com/",
    anchorText: "Visit website",
    domainTraffic: "9.4K",
    domainTrafficNum: 9400,
    pageTraffic: "0",
    pageTrafficNum: 0,
    domainTrust: 45,
    pageTrust: 38,
    keywordsCount: 2,
    firstSeen: "28 Jul 2024",
    lastSeen: "17 Sep 2026",
    status: "Active",
    linkType: "Text",
    isDofollow: false,
    isBestLink: false,
  },
];

// Generate additional backlinks (so excluding subdomains yields exactly 258 backlinks)
const ADDITIONAL_MOCK_BACKLINKS: BacklinkRecord[] = Array.from({ length: 239 }, (_, idx) => {
  const i = idx + 21;
  const isDofollow = i % 4 !== 0;
  const isBestLink = i % 18 === 0;
  const dt = Math.max(12, 92 - (i % 68));
  const pt = Math.max(0, 48 - (i % 38));
  const kw = (i * 3) % 25;
  const trafficNum = (i * 1234) % 850000;
  const trafficStr =
    trafficNum > 1000000
      ? `${(trafficNum / 1000000).toFixed(1)}M`
      : trafficNum > 1000
      ? `${(trafficNum / 1000).toFixed(1)}K`
      : `${trafficNum}`;

  const status: "Active" | "New" | "Lost" =
    i % 12 === 0 ? "Lost" : i % 7 === 0 ? "New" : "Active";

  const anchors = [
    "workcomposer.com",
    "WorkComposer",
    "No text",
    "time tracking app",
    "claims",
    "https://www.workcomposer.com/",
    "time tracking with screen capture",
    "Visit website",
    "employee monitoring software",
    "View Product",
    "Official Pricing",
    "download desktop client",
  ];

  return {
    id: `bl-${i}`,
    sourceTitle: `Productivity Insights and Workforce Metrics Analysis #${i}`,
    sourceUrl: `https://industry-directory-${i % 30}.org/reviews/workcomposer-platform-${i}/`,
    targetUrl: i % 5 === 0 ? "https://www.workcomposer.com/pricing/" : "https://www.workcomposer.com/",
    anchorText: anchors[i % anchors.length],
    domainTraffic: trafficStr,
    domainTrafficNum: trafficNum,
    pageTraffic: "0",
    pageTrafficNum: 0,
    domainTrust: dt,
    pageTrust: pt,
    keywordsCount: kw,
    firstSeen: `${(i % 28) + 1} Jan 2025`,
    lastSeen: `${(i % 28) + 1} Sep 2026`,
    status,
    linkType: "Text",
    isDofollow,
    isBestLink,
  };
});

const SUBDOMAIN_MOCK_BACKLINKS: BacklinkRecord[] = [
  {
    id: "bl-sub-1",
    sourceTitle: "Modern Remote Workforce Tools Review • TechPulse Blog",
    sourceUrl: "https://blog.techpulsenews.com/tools/workcomposer-analysis/",
    targetUrl: "https://www.workcomposer.com/",
    anchorText: "WorkComposer time tracking",
    domainTraffic: "42.1K",
    domainTrafficNum: 42100,
    pageTraffic: "120",
    pageTrafficNum: 120,
    domainTrust: 65,
    pageTrust: 24,
    keywordsCount: 14,
    firstSeen: "10 Feb 2025",
    lastSeen: "18 Sep 2026",
    status: "Active",
    linkType: "Text",
    isDofollow: true,
    isBestLink: false,
  },
  {
    id: "bl-sub-2",
    sourceTitle: "Top 5 Productivity Extensions for Remote Engineers",
    sourceUrl: "https://dev.codersdigest.io/articles/remote-productivity-tools/",
    targetUrl: "https://www.workcomposer.com/features/",
    anchorText: "WorkComposer",
    domainTraffic: "85.3K",
    domainTrafficNum: 85300,
    pageTraffic: "340",
    pageTrafficNum: 340,
    domainTrust: 72,
    pageTrust: 28,
    keywordsCount: 22,
    firstSeen: "22 Mar 2025",
    lastSeen: "21 Sep 2026",
    status: "Active",
    linkType: "Text",
    isDofollow: true,
    isBestLink: true,
  },
  {
    id: "bl-sub-3",
    sourceTitle: "Community Discussion: Automated Screenshots in Remote Teams",
    sourceUrl: "https://forum.sysadmincentral.net/t/automated-screenshot-monitoring/4129",
    targetUrl: "https://www.workcomposer.com/features/auto-screenshots/",
    anchorText: "automated screenshots",
    domainTraffic: "18.4K",
    domainTrafficNum: 18400,
    pageTraffic: "15",
    pageTrafficNum: 15,
    domainTrust: 58,
    pageTrust: 19,
    keywordsCount: 8,
    firstSeen: "14 May 2025",
    lastSeen: "12 Sep 2026",
    status: "Active",
    linkType: "Text",
    isDofollow: false,
    isBestLink: false,
  },
];

export const MOCK_BACKLINKS: BacklinkRecord[] = [
  ...BASE_MOCK_BACKLINKS,
  ...ADDITIONAL_MOCK_BACKLINKS,
  ...SUBDOMAIN_MOCK_BACKLINKS,
];

const SEED_REFERRING_DOMAINS: ReferringDomainRecord[] = [
  {
    id: "rd-1",
    domain: "about.me",
    domainTrust: 94,
    domainTraffic: "916.9K",
    domainTrafficNum: 916900,
    backlinksCount: 1,
    keywords: "999.5K",
    keywordsNum: 999500,
    domainAge: ">10 (15 Sep 2010)",
    firstSeen: "05 Jul 2025",
    lastSeen: "24 Sep 2026",
    status: "Active",
    dofollowCount: 1,
    nofollowCount: 0,
    country: "USA",
    countryCode: "us",
    flag: "🇺🇸",
    ip: "104.16.120.4",
  },
  {
    id: "rd-2",
    domain: "es.gizmodo.com",
    domainTrust: 94,
    domainTraffic: "892.5K",
    domainTrafficNum: 892500,
    backlinksCount: 1,
    keywords: "1M",
    keywordsNum: 1000000,
    domainAge: ">10 (12 Aug 2002)",
    firstSeen: "29 Oct 2025",
    lastSeen: "22 Sep 2026",
    status: "Active",
    dofollowCount: 1,
    nofollowCount: 0,
    country: "Spain",
    countryCode: "es",
    flag: "🇪🇸",
    ip: "151.101.65.67",
  },
  {
    id: "rd-3",
    domain: "www.theregister.com",
    domainTrust: 93,
    domainTraffic: "69.8K",
    domainTrafficNum: 69800,
    backlinksCount: 1,
    keywords: "1.3M",
    keywordsNum: 1300000,
    domainAge: ">10 (04 Jul 1998)",
    firstSeen: "19 Jul 2025",
    lastSeen: "02 Feb 2026",
    status: "Active",
    dofollowCount: 0,
    nofollowCount: 1,
    country: "United Kingdom",
    countryCode: "gb",
    flag: "🇬🇧",
    ip: "199.232.194.133",
  },
  {
    id: "rd-4",
    domain: "www.makeuseof.com",
    domainTrust: 91,
    domainTraffic: "1.2M",
    domainTrafficNum: 1200000,
    backlinksCount: 1,
    keywords: "7.8M",
    keywordsNum: 7800000,
    domainAge: ">10 (24 Jun 2006)",
    firstSeen: "08 Dec 2025",
    lastSeen: "05 May 2026",
    status: "Active",
    dofollowCount: 1,
    nofollowCount: 0,
    country: "Canada",
    countryCode: "ca",
    flag: "🇨🇦",
    ip: "104.18.28.112",
  },
  {
    id: "rd-5",
    domain: "www.trustradius.com",
    domainTrust: 91,
    domainTraffic: "108.5K",
    domainTrafficNum: 108500,
    backlinksCount: 1,
    keywords: "1.4M",
    keywordsNum: 1400000,
    domainAge: ">10 (18 Feb 2012)",
    firstSeen: "10 Jul 2025",
    lastSeen: "20 Sep 2026",
    status: "Active",
    dofollowCount: 1,
    nofollowCount: 0,
    country: "USA",
    countryCode: "us",
    flag: "🇺🇸",
    ip: "104.26.8.212",
  },
  {
    id: "rd-6",
    domain: "www.provenexpert.com",
    domainTrust: 91,
    domainTraffic: "143.1K",
    domainTrafficNum: 143100,
    backlinksCount: 2,
    keywords: "551.1K",
    keywordsNum: 551100,
    domainAge: ">10 (21 Dec 2012)",
    firstSeen: "17 Jul 2025",
    lastSeen: "23 Sep 2026",
    status: "Active",
    dofollowCount: 2,
    nofollowCount: 0,
    country: "Germany",
    countryCode: "de",
    flag: "🇩🇪",
    ip: "172.67.199.34",
  },
  {
    id: "rd-7",
    domain: "www.manageengine.com",
    domainTrust: 90,
    domainTraffic: "264.4K",
    domainTrafficNum: 264400,
    backlinksCount: 2,
    keywords: "1.8M",
    keywordsNum: 1800000,
    domainAge: ">10 (08 Nov 2002)",
    firstSeen: "10 Nov 2025",
    lastSeen: "19 Sep 2026",
    status: "Active",
    dofollowCount: 2,
    nofollowCount: 0,
    country: "USA",
    countryCode: "us",
    flag: "🇺🇸",
    ip: "136.143.190.11",
  },
  {
    id: "rd-8",
    domain: "coda.io",
    domainTrust: 90,
    domainTraffic: "228.3K",
    domainTrafficNum: 228300,
    backlinksCount: 3,
    keywords: "303.4K",
    keywordsNum: 303400,
    domainAge: ">10 (12 May 2014)",
    firstSeen: "21 Sep 2025",
    lastSeen: "18 Sep 2026",
    status: "Active",
    dofollowCount: 3,
    nofollowCount: 0,
    country: "USA",
    countryCode: "us",
    flag: "🇺🇸",
    ip: "104.18.23.11",
  },
  {
    id: "rd-9",
    domain: "www.xataka.com",
    domainTrust: 89,
    domainTraffic: "7.4M",
    domainTrafficNum: 7400000,
    backlinksCount: 1,
    keywords: "8M",
    keywordsNum: 8000000,
    domainAge: ">10 (15 Apr 2004)",
    firstSeen: "12 Jul 2025",
    lastSeen: "20 Dec 2025",
    status: "Active",
    dofollowCount: 1,
    nofollowCount: 0,
    country: "Spain",
    countryCode: "es",
    flag: "🇪🇸",
    ip: "151.101.193.67",
  },
  {
    id: "rd-10",
    domain: "www.intensedebate.com",
    domainTrust: 89,
    domainTraffic: "288",
    domainTrafficNum: 288,
    backlinksCount: 1,
    keywords: "875",
    keywordsNum: 875,
    domainAge: ">10 (03 Oct 2006)",
    firstSeen: "17 Jul 2025",
    lastSeen: "21 Sep 2026",
    status: "Active",
    dofollowCount: 0,
    nofollowCount: 1,
    country: "USA",
    countryCode: "us",
    flag: "🇺🇸",
    ip: "192.0.78.13",
  },
  {
    id: "rd-11",
    domain: "www.elephantjournal.c...",
    domainTrust: 88,
    domainTraffic: "14.3K",
    domainTrafficNum: 14300,
    backlinksCount: 2,
    keywords: "200.9K",
    keywordsNum: 200900,
    domainAge: ">10 (05 Jan 2002)",
    firstSeen: "02 Jun 2025",
    lastSeen: "22 Sep 2026",
    status: "Active",
    dofollowCount: 2,
    nofollowCount: 0,
    country: "USA",
    countryCode: "us",
    flag: "🇺🇸",
    ip: "104.26.15.112",
  },
  {
    id: "rd-12",
    domain: "www.saashub.com",
    domainTrust: 87,
    domainTraffic: "206.6K",
    domainTrafficNum: 206600,
    backlinksCount: 27,
    keywords: "849.1K",
    keywordsNum: 849100,
    domainAge: ">10 (25 Nov 2009)",
    firstSeen: "03 Mar 2024",
    lastSeen: "24 Sep 2026",
    status: "Active",
    dofollowCount: 25,
    nofollowCount: 2,
    country: "Singapore",
    countryCode: "sg",
    flag: "🇸🇬",
    ip: "104.21.48.12",
  },
  {
    id: "rd-13",
    domain: "www.xataka.com.mx",
    domainTrust: 86,
    domainTraffic: "213.8K",
    domainTrafficNum: 213800,
    backlinksCount: 1,
    keywords: "867.5K",
    keywordsNum: 867500,
    domainAge: ">10 (19 Feb 2013)",
    firstSeen: "16 Aug 2025",
    lastSeen: "20 Sep 2026",
    status: "Active",
    dofollowCount: 1,
    nofollowCount: 0,
    country: "Mexico",
    countryCode: "mx",
    flag: "🇲🇽",
    ip: "151.101.129.67",
  },
  {
    id: "rd-14",
    domain: "dailygalaxy.com",
    domainTrust: 86,
    domainTraffic: "669",
    domainTrafficNum: 669,
    backlinksCount: 1,
    keywords: "136.7K",
    keywordsNum: 136700,
    domainAge: ">10 (28 Jan 2007)",
    firstSeen: "31 Oct 2025",
    lastSeen: "21 Sep 2026",
    status: "Active",
    dofollowCount: 1,
    nofollowCount: 0,
    country: "USA",
    countryCode: "us",
    flag: "🇺🇸",
    ip: "172.67.144.11",
  },
  {
    id: "rd-15",
    domain: "www.softwareworld.co",
    domainTrust: 85,
    domainTraffic: "208.2K",
    domainTrafficNum: 208200,
    backlinksCount: 2,
    keywords: "932.3K",
    keywordsNum: 932300,
    domainAge: ">10 (11 Mar 2014)",
    firstSeen: "29 Sep 2025",
    lastSeen: "23 Sep 2026",
    status: "Active",
    dofollowCount: 2,
    nofollowCount: 0,
    country: "India",
    countryCode: "in",
    flag: "🇮🇳",
    ip: "104.21.32.99",
  },
  {
    id: "rd-16",
    domain: "doodleordie.com",
    domainTrust: 84,
    domainTraffic: "140",
    domainTrafficNum: 140,
    backlinksCount: 1,
    keywords: "1.7K",
    keywordsNum: 1700,
    domainAge: ">10 (18 Nov 2011)",
    firstSeen: "01 Dec 2025",
    lastSeen: "19 Sep 2026",
    status: "Active",
    dofollowCount: 0,
    nofollowCount: 1,
    country: "USA",
    countryCode: "us",
    flag: "🇺🇸",
    ip: "104.28.16.44",
  },
  {
    id: "rd-17",
    domain: "www.rohitab.com",
    domainTrust: 84,
    domainTraffic: "712",
    domainTrafficNum: 712,
    backlinksCount: 8,
    keywords: "7.2K",
    keywordsNum: 7200,
    domainAge: ">10 (01 Jan 1999)",
    firstSeen: "17 Jul 2025",
    lastSeen: "20 Sep 2026",
    status: "Active",
    dofollowCount: 7,
    nofollowCount: 1,
    country: "USA",
    countryCode: "us",
    flag: "🇺🇸",
    ip: "198.54.117.210",
  },
  {
    id: "rd-18",
    domain: "www.example3.com",
    domainTrust: 83,
    domainTraffic: "535",
    domainTrafficNum: 535,
    backlinksCount: 2,
    keywords: "1.4K",
    keywordsNum: 1400,
    domainAge: ">10 (09 Oct 2012)",
    firstSeen: "11 Nov 2025",
    lastSeen: "19 Sep 2026",
    status: "Active",
    dofollowCount: 2,
    nofollowCount: 0,
    country: "USA",
    countryCode: "us",
    flag: "🇺🇸",
    ip: "93.184.216.34",
  },
  {
    id: "rd-19",
    domain: "la.dental-tribune.com",
    domainTrust: 82,
    domainTraffic: "1.3K",
    domainTrafficNum: 1300,
    backlinksCount: 1,
    keywords: "11.3K",
    keywordsNum: 11300,
    domainAge: ">10 (14 Jul 2004)",
    firstSeen: "08 Jul 2025",
    lastSeen: "18 Sep 2026",
    status: "Active",
    dofollowCount: 1,
    nofollowCount: 0,
    country: "Germany",
    countryCode: "de",
    flag: "🇩🇪",
    ip: "185.53.178.6",
  },
  {
    id: "rd-20",
    domain: "blog.elhacker.net",
    domainTrust: 79,
    domainTraffic: "6.8K",
    domainTrafficNum: 6800,
    backlinksCount: 1,
    keywords: "45.6K",
    keywordsNum: 45600,
    domainAge: ">10 (22 Aug 2003)",
    firstSeen: "13 Jul 2025",
    lastSeen: "17 Sep 2026",
    status: "Active",
    dofollowCount: 1,
    nofollowCount: 0,
    country: "Spain",
    countryCode: "es",
    flag: "🇪🇸",
    ip: "172.67.201.88",
  },
];

const ADDITIONAL_REFERRING_DOMAINS: ReferringDomainRecord[] = [
  {
    id: "rd-21",
    domain: "techreviewdaily.io",
    domainTrust: 78,
    domainTraffic: "19.4K",
    domainTrafficNum: 19400,
    backlinksCount: 14,
    keywords: "84.2K",
    keywordsNum: 84200,
    domainAge: "6 yrs (14 Jan 2020)",
    firstSeen: "14 Jan 2024",
    lastSeen: "23 Sep 2026",
    status: "Active",
    dofollowCount: 12,
    nofollowCount: 2,
    country: "Singapore",
    countryCode: "sg",
    flag: "🇸🇬",
    ip: "104.21.48.12",
  },
  {
    id: "rd-22",
    domain: "saasdirectory.com",
    domainTrust: 77,
    domainTraffic: "42.8K",
    domainTrafficNum: 42800,
    backlinksCount: 28,
    keywords: "195.4K",
    keywordsNum: 195400,
    domainAge: "8 yrs (20 Feb 2018)",
    firstSeen: "20 Feb 2024",
    lastSeen: "22 Sep 2026",
    status: "Active",
    dofollowCount: 26,
    nofollowCount: 2,
    country: "USA",
    countryCode: "us",
    flag: "🇺🇸",
    ip: "172.67.182.44",
  },
  ...Array.from({ length: 158 }, (_, idx) => {
    const i = idx + 23;
    const dt = Math.max(14, 76 - Math.floor(i * 0.36));
    const trafficNum = ((i * 3421) % 450000) + 120;
    const trafficStr =
      trafficNum > 1000000
        ? `${(trafficNum / 1000000).toFixed(1)}M`
        : trafficNum > 1000
        ? `${(trafficNum / 1000).toFixed(1)}K`
        : `${trafficNum}`;
    const kwNum = ((i * 5642) % 680000) + 450;
    const kwStr =
      kwNum > 1000000
        ? `${(kwNum / 1000000).toFixed(1)}M`
        : kwNum > 1000
        ? `${(kwNum / 1000).toFixed(1)}K`
        : `${kwNum}`;
    const blCount = i % 7 === 0 ? (i % 25) + 3 : i % 3 === 0 ? 2 : 1;
    const years = (i % 15) + 1;
    const age =
      years > 10
        ? `>10 (${(i % 28) + 1} May 2012)`
        : `${years} yrs (${(i % 28) + 1} Jun ${2026 - years})`;
    const months = ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"];
    const countries = ["USA", "Germany", "United Kingdom", "France", "Singapore", "Canada", "Australia"];
    const countryCodes = ["us", "de", "gb", "fr", "sg", "ca", "au"];
    const flags = ["🇺🇸", "🇩🇪", "🇬🇧", "🇫🇷", "🇸🇬", "🇨🇦", "🇦🇺"];

    return {
      id: `rd-${i}`,
      domain: `industry-resource-${i}.com`,
      domainTrust: dt,
      domainTraffic: trafficStr,
      domainTrafficNum: trafficNum,
      backlinksCount: blCount,
      keywords: kwStr,
      keywordsNum: kwNum,
      domainAge: age,
      firstSeen: `${(i % 28) + 1} ${months[i % 12]} 2025`,
      lastSeen: `${(i % 28) + 1} Sep 2026`,
      status: "Active" as const,
      dofollowCount: blCount,
      nofollowCount: 0,
      country: countries[i % countries.length],
      countryCode: countryCodes[i % countryCodes.length],
      flag: flags[i % flags.length],
      ip: `104.${(i * 3) % 255}.${(i * 7) % 255}.${(i * 11) % 255}`,
    };
  }),
];

const NEW_REFERRING_DOMAINS: ReferringDomainRecord[] = Array.from({ length: 14 }, (_, idx) => {
  const i = idx + 181;
  return {
    id: `rd-new-${i}`,
    domain: `new-partner-${idx + 1}.org`,
    domainTrust: 65 - idx,
    domainTraffic: `${((idx + 3) * 1.4).toFixed(1)}K`,
    domainTrafficNum: (idx + 3) * 1400,
    backlinksCount: 1,
    keywords: `${((idx + 5) * 2.1).toFixed(1)}K`,
    keywordsNum: (idx + 5) * 2100,
    domainAge: "2 yrs (10 Aug 2024)",
    firstSeen: `${idx + 10} Sep 2026`,
    lastSeen: "24 Sep 2026",
    status: "New" as const,
    country: "USA",
    countryCode: "us",
    flag: "🇺🇸",
    ip: `198.51.100.${idx + 1}`,
  };
});

const LOST_REFERRING_DOMAINS: ReferringDomainRecord[] = Array.from({ length: 9 }, (_, idx) => {
  const i = idx + 195;
  return {
    id: `rd-lost-${i}`,
    domain: `deprecated-directory-${idx + 1}.io`,
    domainTrust: 45 - idx,
    domainTraffic: "450",
    domainTrafficNum: 450,
    backlinksCount: 1,
    keywords: "1.2K",
    keywordsNum: 1200,
    domainAge: "5 yrs (15 Jan 2021)",
    firstSeen: "10 Jan 2024",
    lastSeen: `0${idx + 1} Sep 2026`,
    status: "Lost" as const,
    country: "United Kingdom",
    countryCode: "gb",
    flag: "🇬🇧",
    ip: `203.0.113.${idx + 1}`,
  };
});

export const MOCK_REFERRING_DOMAINS: ReferringDomainRecord[] = [
  ...SEED_REFERRING_DOMAINS,
  ...ADDITIONAL_REFERRING_DOMAINS,
  ...NEW_REFERRING_DOMAINS,
  ...LOST_REFERRING_DOMAINS,
].map((item, idx) => {
  const pt = item.pageTrust ?? Math.max(15, Math.min(96, item.domainTrust - ((idx % 7) - 3)));
  const ltNum = item.linkTrafficNum ?? Math.round(item.domainTrafficNum * 0.12);
  const lt = item.linkTraffic ?? (ltNum >= 1000000 ? `${(ltNum / 1000000).toFixed(1)}M` : ltNum >= 1000 ? `${(ltNum / 1000).toFixed(1)}K` : `${ltNum}`);
  const bkNum = item.backlinkKeywordsNum ?? Math.round(item.keywordsNum * 0.08);
  const bk = item.backlinkKeywords ?? (bkNum >= 1000000 ? `${(bkNum / 1000000).toFixed(1)}M` : bkNum >= 1000 ? `${(bkNum / 1000).toFixed(1)}K` : `${bkNum}`);
  const dofollow = item.dofollowCount ?? (idx % 4 === 0 ? 0 : Math.max(1, Math.floor(item.backlinksCount * 0.75)));
  const nofollow = item.nofollowCount ?? Math.max(0, item.backlinksCount - dofollow);
  return {
    ...item,
    pageTrust: pt,
    linkTraffic: lt,
    linkTrafficNum: ltNum,
    backlinkKeywords: bk,
    backlinkKeywordsNum: bkNum,
    dofollowCount: dofollow,
    nofollowCount: nofollow,
  };
});

export const MOCK_PAGES: PageRecord[] = [
  {
    id: "page-1",
    url: "https://www.workcomposer.com/",
    title: "WorkComposer - Time Tracking & Employee Monitoring Software",
    backlinksCount: 142,
    refDomainsCount: 98,
    domainTrust: 38,
    statusCode: 200,
  },
  {
    id: "page-2",
    url: "https://www.workcomposer.com/features/work-time-tracking/",
    title: "Automated Work Time Tracking Features",
    backlinksCount: 46,
    refDomainsCount: 32,
    domainTrust: 38,
    statusCode: 200,
  },
  {
    id: "page-3",
    url: "https://www.workcomposer.com/wc/time-and-screenshot-tracking-software/",
    title: "Screenshot Tracking & Proof of Work",
    backlinksCount: 34,
    refDomainsCount: 26,
    domainTrust: 38,
    statusCode: 200,
  },
  {
    id: "page-4",
    url: "https://www.workcomposer.com/features/web-and-app-tracking/",
    title: "Web and Application Usage Analytics",
    backlinksCount: 18,
    refDomainsCount: 16,
    domainTrust: 38,
    statusCode: 200,
  },
  {
    id: "page-5",
    url: "https://www.workcomposer.com/pricing/",
    title: "Flexible Pricing for Teams of All Sizes",
    backlinksCount: 10,
    refDomainsCount: 9,
    domainTrust: 38,
    statusCode: 200,
  },
];

export const MOCK_IPS: IpRecord[] = [
  {
    id: "ip-1",
    ipAddress: "104.21.48.12",
    subnet: "104.21.48.0/24",
    country: "Singapore",
    countryCode: "sg",
    flag: "🇸🇬",
    refDomainsCount: 28,
    backlinksCount: 54,
  },
  {
    id: "ip-2",
    ipAddress: "172.67.182.44",
    subnet: "172.67.182.0/24",
    country: "USA",
    countryCode: "us",
    flag: "🇺🇸",
    refDomainsCount: 22,
    backlinksCount: 48,
  },
  {
    id: "ip-3",
    ipAddress: "104.26.11.230",
    subnet: "104.26.11.0/24",
    country: "Singapore",
    countryCode: "sg",
    flag: "🇸🇬",
    refDomainsCount: 18,
    backlinksCount: 36,
  },
  {
    id: "ip-4",
    ipAddress: "185.199.108.153",
    subnet: "185.199.108.0/24",
    country: "USA",
    countryCode: "us",
    flag: "🇺🇸",
    refDomainsCount: 12,
    backlinksCount: 24,
  },
  {
    id: "ip-5",
    ipAddress: "194.247.12.8",
    subnet: "194.247.12.0/24",
    country: "Moldova",
    countryCode: "md",
    flag: "🇲🇩",
    refDomainsCount: 16,
    backlinksCount: 22,
  },
];

export interface ZohoPageItem {
  id: string;
  url: string;
  protocol: "https" | "http";
  backlinksCount: number;
  refDomainsCount: number;
  brokenBacklinksCount?: number;
  domainTrust?: number;
  statusCode?: number;
  firstSeen?: string;
  lastSeen?: string;
  sampleRefDomains?: { domain: string; dt: number; links: number }[];
  sampleBacklinks?: { sourceUrl: string; targetUrl: string; anchor: string; isDofollow: boolean }[];
}

export const MOCK_ZOHO_PAGES: ZohoPageItem[] = [
  {
    id: "zoho-p-1",
    url: "https://workco.com/",
    protocol: "https",
    backlinksCount: 36,
    refDomainsCount: 30,
    brokenBacklinksCount: 0,
    domainTrust: 65,
    statusCode: 200,
    firstSeen: "12 Oct 2021",
    lastSeen: "23 Sep 2026",
    sampleRefDomains: [
      { domain: "buffer.com", dt: 88, links: 4 },
      { domain: "sproutsocial.com", dt: 89, links: 3 },
      { domain: "hubspot.com", dt: 93, links: 2 },
      { domain: "techcrunch.com", dt: 92, links: 1 },
      { domain: "forbes.com", dt: 94, links: 1 },
    ],
    sampleBacklinks: [
      { sourceUrl: "https://buffer.com/resources/social-media-management-tools", targetUrl: "https://workco.com/", anchor: "WorkCo Digital platform", isDofollow: true },
      { sourceUrl: "https://sproutsocial.com/insights/best-social-media-tools", targetUrl: "https://workco.com/", anchor: "https://workco.com/", isDofollow: true },
      { sourceUrl: "https://blog.hubspot.com/marketing/social-publishing-software", targetUrl: "https://workco.com/", anchor: "social media suite", isDofollow: false },
    ],
  },
  {
    id: "zoho-p-2",
    url: "http://workco.com/",
    protocol: "http",
    backlinksCount: 24,
    refDomainsCount: 6,
    brokenBacklinksCount: 0,
    domainTrust: 52,
    statusCode: 301,
    firstSeen: "04 May 2019",
    lastSeen: "20 Sep 2026",
    sampleRefDomains: [
      { domain: "producthunt.com", dt: 90, links: 8 },
      { domain: "g2.com", dt: 89, links: 6 },
      { domain: "capterra.com", dt: 87, links: 5 },
    ],
    sampleBacklinks: [
      { sourceUrl: "https://www.producthunt.com/products/zoho-social-2", targetUrl: "http://workco.com/", anchor: "workco.com", isDofollow: true },
      { sourceUrl: "https://www.g2.com/products/zoho-social/reviews", targetUrl: "http://workco.com/", anchor: "Visit Website", isDofollow: false },
    ],
  },
  {
    id: "zoho-p-3",
    url: "https://www.workco.com/",
    protocol: "https",
    backlinksCount: 2,
    refDomainsCount: 2,
    brokenBacklinksCount: 0,
    domainTrust: 48,
    statusCode: 301,
    firstSeen: "18 Aug 2022",
    lastSeen: "15 Sep 2026",
    sampleRefDomains: [
      { domain: "medium.com", dt: 91, links: 1 },
      { domain: "reddit.com", dt: 92, links: 1 },
    ],
    sampleBacklinks: [
      { sourceUrl: "https://medium.com/@marketingguru/tools-for-scheduling-2024", targetUrl: "https://www.workco.com/", anchor: "www.workco.com", isDofollow: true },
    ],
  },
  {
    id: "zoho-p-4",
    url: "http://www.workco.com/",
    protocol: "http",
    backlinksCount: 3,
    refDomainsCount: 2,
    brokenBacklinksCount: 0,
    domainTrust: 44,
    statusCode: 301,
    firstSeen: "10 Feb 2020",
    lastSeen: "12 Sep 2026",
    sampleRefDomains: [
      { domain: "quora.com", dt: 90, links: 2 },
      { domain: "trustradius.com", dt: 82, links: 1 },
    ],
    sampleBacklinks: [
      { sourceUrl: "https://www.quora.com/What-is-the-best-social-media-tool", targetUrl: "http://www.workco.com/", anchor: "http://www.workco.com/", isDofollow: true },
    ],
  },
];

export const MOCK_WORKCOMPOSER_PAGES: ZohoPageItem[] = [
  {
    id: "wc-p-1",
    url: "https://workcomposer.com/",
    protocol: "https",
    backlinksCount: 77,
    refDomainsCount: 65,
    brokenBacklinksCount: 0,
    domainTrust: 42,
    statusCode: 200,
    firstSeen: "18 Nov 2022",
    lastSeen: "26 Sep 2026",
    sampleRefDomains: [
      { domain: "techcrunch.com", dt: 92, links: 12 },
      { domain: "makeuseof.com", dt: 91, links: 8 },
      { domain: "xataka.com", dt: 89, links: 6 },
    ],
    sampleBacklinks: [
      { sourceUrl: "https://makeuseof.com/best-apps-to-reduce-overtime-work/", targetUrl: "https://workcomposer.com/", anchor: "WorkComposer", isDofollow: true },
    ],
  },
  {
    id: "wc-p-2",
    url: "http://workcomposer.com/",
    protocol: "http",
    backlinksCount: 50,
    refDomainsCount: 50,
    brokenBacklinksCount: 0,
    domainTrust: 40,
    statusCode: 200,
    firstSeen: "18 Nov 2022",
    lastSeen: "26 Sep 2026",
    sampleRefDomains: [
      { domain: "g2.com", dt: 89, links: 10 },
      { domain: "capterra.com", dt: 87, links: 8 },
    ],
    sampleBacklinks: [
      { sourceUrl: "https://g2.com/products/workcomposer/reviews", targetUrl: "http://workcomposer.com/", anchor: "workcomposer.com", isDofollow: true },
    ],
  },
  {
    id: "wc-p-3",
    url: "https://www.workcomposer.com/",
    protocol: "https",
    backlinksCount: 87,
    refDomainsCount: 34,
    brokenBacklinksCount: 1,
    domainTrust: 38,
    statusCode: 200,
    firstSeen: "18 Nov 2022",
    lastSeen: "26 Sep 2026",
    sampleRefDomains: [
      { domain: "softwareadvice.com", dt: 85, links: 6 },
    ],
    sampleBacklinks: [
      { sourceUrl: "https://softwareadvice.com/time-tracking", targetUrl: "https://www.workcomposer.com/", anchor: "WorkComposer", isDofollow: true },
    ],
  },
  {
    id: "wc-p-4",
    url: "http://www.workcomposer.com/",
    protocol: "http",
    backlinksCount: 23,
    refDomainsCount: 15,
    brokenBacklinksCount: 0,
    domainTrust: 36,
    statusCode: 200,
    firstSeen: "18 Nov 2022",
    lastSeen: "26 Sep 2026",
    sampleRefDomains: [{ domain: "medium.com", dt: 91, links: 4 }],
    sampleBacklinks: [{ sourceUrl: "https://medium.com/remote-work-tips", targetUrl: "http://www.workcomposer.com/", anchor: "time tracking", isDofollow: true }],
  },
  {
    id: "wc-p-5",
    url: "https://workcomposer.com/features/privacy-and-security/",
    protocol: "https",
    backlinksCount: 18,
    refDomainsCount: 12,
    brokenBacklinksCount: 0,
    domainTrust: 38,
    statusCode: 200,
    firstSeen: "20 Mar 2023",
    lastSeen: "21 Sep 2026",
    sampleRefDomains: [{ domain: "reddit.com", dt: 96, links: 3 }],
    sampleBacklinks: [{ sourceUrl: "https://reddit.com/r/productivity", targetUrl: "https://workcomposer.com/features/privacy-and-security/", anchor: "screenshot monitoring", isDofollow: true }],
  },
  {
    id: "wc-p-6",
    url: "https://www.workcomposer.com/features/web-and-app-tracking/",
    protocol: "https",
    backlinksCount: 12,
    refDomainsCount: 10,
    brokenBacklinksCount: 0,
    domainTrust: 38,
    statusCode: 200,
    firstSeen: "10 Apr 2023",
    lastSeen: "18 Sep 2026",
    sampleRefDomains: [{ domain: "quora.com", dt: 91, links: 2 }],
    sampleBacklinks: [{ sourceUrl: "https://quora.com/best-monitoring-tools", targetUrl: "https://www.workcomposer.com/features/web-and-app-tracking/", anchor: "app tracking", isDofollow: true }],
  },
  {
    id: "wc-p-7",
    url: "https://www.workcomposer.com/pricing/",
    protocol: "https",
    backlinksCount: 9,
    refDomainsCount: 8,
    brokenBacklinksCount: 0,
    domainTrust: 38,
    statusCode: 200,
    firstSeen: "01 May 2023",
    lastSeen: "15 Sep 2026",
    sampleRefDomains: [{ domain: "trustpilot.com", dt: 90, links: 2 }],
    sampleBacklinks: [{ sourceUrl: "https://trustpilot.com/review/workcomposer.com", targetUrl: "https://www.workcomposer.com/pricing/", anchor: "pricing", isDofollow: true }],
  },
  {
    id: "wc-p-8",
    url: "https://www.workcomposer.com/download/",
    protocol: "https",
    backlinksCount: 7,
    refDomainsCount: 6,
    brokenBacklinksCount: 0,
    domainTrust: 38,
    statusCode: 200,
    firstSeen: "12 May 2023",
    lastSeen: "10 Sep 2026",
    sampleRefDomains: [{ domain: "softpedia.com", dt: 88, links: 3 }],
    sampleBacklinks: [{ sourceUrl: "https://softpedia.com/get/workcomposer", targetUrl: "https://www.workcomposer.com/download/", anchor: "download client", isDofollow: true }],
  },
  {
    id: "wc-p-9",
    url: "https://www.workcomposer.com/features/auto-screenshots/",
    protocol: "https",
    backlinksCount: 5,
    refDomainsCount: 4,
    brokenBacklinksCount: 0,
    domainTrust: 38,
    statusCode: 200,
    firstSeen: "19 Jul 2023",
    lastSeen: "05 Sep 2026",
    sampleRefDomains: [{ domain: "theregister.com", dt: 93, links: 1 }],
    sampleBacklinks: [{ sourceUrl: "https://theregister.com/security_news", targetUrl: "https://www.workcomposer.com/features/auto-screenshots/", anchor: "scheduled screenshot capture", isDofollow: false }],
  },
  {
    id: "wc-p-10",
    url: "https://www.workcomposer.com/blog/how-to-track-remote-employees/",
    protocol: "https",
    backlinksCount: 4,
    refDomainsCount: 4,
    brokenBacklinksCount: 0,
    domainTrust: 38,
    statusCode: 200,
    firstSeen: "25 Aug 2023",
    lastSeen: "01 Sep 2026",
    sampleRefDomains: [{ domain: "linkedin.com", dt: 98, links: 2 }],
    sampleBacklinks: [{ sourceUrl: "https://linkedin.com/pulse/remote-efficiency", targetUrl: "https://www.workcomposer.com/blog/how-to-track-remote-employees/", anchor: "track remote workers", isDofollow: true }],
  },
  {
    id: "wc-p-11",
    url: "https://www.workcomposer.com/contact/",
    protocol: "https",
    backlinksCount: 3,
    refDomainsCount: 3,
    brokenBacklinksCount: 0,
    domainTrust: 38,
    statusCode: 200,
    firstSeen: "05 Sep 2023",
    lastSeen: "28 Aug 2026",
    sampleRefDomains: [{ domain: "clutch.co", dt: 89, links: 1 }],
    sampleBacklinks: [{ sourceUrl: "https://clutch.co/profile/workcomposer", targetUrl: "https://www.workcomposer.com/contact/", anchor: "contact WorkComposer", isDofollow: true }],
  },
  {
    id: "wc-p-12",
    url: "https://www.workcomposer.com/privacy-policy/",
    protocol: "https",
    backlinksCount: 2,
    refDomainsCount: 2,
    brokenBacklinksCount: 0,
    domainTrust: 38,
    statusCode: 200,
    firstSeen: "10 Oct 2023",
    lastSeen: "20 Aug 2026",
    sampleRefDomains: [{ domain: "termsfeed.com", dt: 82, links: 1 }],
    sampleBacklinks: [{ sourceUrl: "https://termsfeed.com/live/workcomposer", targetUrl: "https://www.workcomposer.com/privacy-policy/", anchor: "privacy policy", isDofollow: true }],
  },
  {
    id: "wc-p-13",
    url: "https://www.workcomposer.com/terms-of-service/",
    protocol: "https",
    backlinksCount: 1,
    refDomainsCount: 1,
    brokenBacklinksCount: 0,
    domainTrust: 38,
    statusCode: 200,
    firstSeen: "15 Oct 2023",
    lastSeen: "15 Aug 2026",
    sampleRefDomains: [{ domain: "termsfeed.com", dt: 82, links: 1 }],
    sampleBacklinks: [{ sourceUrl: "https://termsfeed.com/live/terms", targetUrl: "https://www.workcomposer.com/terms-of-service/", anchor: "terms", isDofollow: true }],
  },
];

export interface ZohoIpItem {
  id: string;
  ipAddress: string;
  subnet: string;
  country: string;
  countryCode: string;
  flag: string;
  logoType?: string;
  ipCountInSubnet?: number;
  refDomainsCount: number;
  backlinksCount: number;
  sampleRefDomains?: { domain: string; dt: number; links: number }[];
  sampleBacklinks?: { sourceUrl: string; targetUrl: string; anchor: string; isDofollow: boolean }[];
}

export const MOCK_ZOHO_IPS: ZohoIpItem[] = [
  {
    id: "ip-z-1",
    ipAddress: "195.20.19.178",
    subnet: "195.20.19.0/24",
    country: "Romania",
    countryCode: "ro",
    flag: "🇷🇴",
    refDomainsCount: 15,
    backlinksCount: 16,
    sampleRefDomains: [
      { domain: "techhub-eu.ro", dt: 64, links: 4 },
      { domain: "digitaleu.org", dt: 58, links: 3 },
      { domain: "socialnews.ro", dt: 52, links: 3 },
    ],
    sampleBacklinks: [
      { sourceUrl: "https://techhub-eu.ro/top-tools-2026", targetUrl: "https://workco.com/", anchor: "WorkCo Digital", isDofollow: true },
    ],
  },
  {
    id: "ip-z-2",
    ipAddress: "45.13.58.15",
    subnet: "45.13.58.0/24",
    country: "Germany",
    countryCode: "de",
    flag: "🇩🇪",
    refDomainsCount: 3,
    backlinksCount: 4,
    sampleRefDomains: [
      { domain: "marketing-berlin.de", dt: 61, links: 2 },
      { domain: "techverband.de", dt: 70, links: 2 },
    ],
    sampleBacklinks: [
      { sourceUrl: "https://marketing-berlin.de/software", targetUrl: "https://workco.com/", anchor: "workco.com", isDofollow: true },
    ],
  },
  {
    id: "ip-z-3",
    ipAddress: "24.199.114.38",
    subnet: "24.199.114.0/24",
    country: "United States",
    countryCode: "us",
    flag: "🇺🇸",
    refDomainsCount: 3,
    backlinksCount: 7,
    sampleRefDomains: [
      { domain: "cloudtimes.io", dt: 72, links: 4 },
      { domain: "startupsuite.co", dt: 68, links: 3 },
    ],
    sampleBacklinks: [
      { sourceUrl: "https://cloudtimes.io/review/zoho", targetUrl: "https://workco.com/", anchor: "WorkCo Digital review", isDofollow: true },
    ],
  },
  {
    id: "ip-z-4",
    ipAddress: "152.53.38.228",
    subnet: "152.53.38.0/24",
    country: "Singapore",
    countryCode: "sg",
    flag: "🇸🇬",
    refDomainsCount: 2,
    backlinksCount: 2,
    sampleRefDomains: [
      { domain: "techinsingapore.sg", dt: 59, links: 1 },
      { domain: "asia-saas.com", dt: 65, links: 1 },
    ],
    sampleBacklinks: [
      { sourceUrl: "https://techinsingapore.sg/saas-leaders", targetUrl: "https://workco.com/", anchor: "WorkCo Digital", isDofollow: true },
    ],
  },
  {
    id: "ip-z-5",
    ipAddress: "192.124.249.58",
    subnet: "192.124.249.0/24",
    country: "Austria",
    countryCode: "at",
    flag: "🇦🇹",
    refDomainsCount: 1,
    backlinksCount: 1,
    sampleRefDomains: [{ domain: "vienna-digital.at", dt: 54, links: 1 }],
    sampleBacklinks: [{ sourceUrl: "https://vienna-digital.at/post/social", targetUrl: "https://workco.com/", anchor: "social media suite", isDofollow: true }],
  },
  {
    id: "ip-z-6",
    ipAddress: "74.208.236.184",
    subnet: "74.208.236.0/24",
    country: "United States",
    countryCode: "us",
    flag: "🇺🇸",
    refDomainsCount: 1,
    backlinksCount: 2,
    sampleRefDomains: [{ domain: "usbusinesshub.net", dt: 62, links: 2 }],
    sampleBacklinks: [{ sourceUrl: "https://usbusinesshub.net/directory", targetUrl: "https://workco.com/", anchor: "https://workco.com/", isDofollow: true }],
  },
  {
    id: "ip-z-7",
    ipAddress: "23.227.38.65",
    subnet: "23.227.38.0/24",
    country: "Denmark",
    countryCode: "dk",
    flag: "🇩🇰",
    refDomainsCount: 1,
    backlinksCount: 1,
    sampleRefDomains: [{ domain: "nordicgrowth.dk", dt: 57, links: 1 }],
    sampleBacklinks: [{ sourceUrl: "https://nordicgrowth.dk/tools", targetUrl: "https://workco.com/", anchor: "WorkCo Digital", isDofollow: false }],
  },
  {
    id: "ip-z-8",
    ipAddress: "46.202.168.212",
    subnet: "46.202.168.0/24",
    country: "France",
    countryCode: "fr",
    flag: "🇫🇷",
    refDomainsCount: 1,
    backlinksCount: 10,
    sampleRefDomains: [{ domain: "leparisien-tech.fr", dt: 75, links: 10 }],
    sampleBacklinks: [{ sourceUrl: "https://leparisien-tech.fr/comparatif", targetUrl: "https://workco.com/", anchor: "outil de gestion", isDofollow: true }],
  },
  {
    id: "ip-z-9",
    ipAddress: "217.182.220.21",
    subnet: "217.182.220.0/24",
    country: "France",
    countryCode: "fr",
    flag: "🇫🇷",
    refDomainsCount: 1,
    backlinksCount: 6,
    sampleRefDomains: [{ domain: "reseaux-sociaux.fr", dt: 68, links: 6 }],
    sampleBacklinks: [{ sourceUrl: "https://reseaux-sociaux.fr/logiciels", targetUrl: "https://workco.com/", anchor: "WorkCo Digital", isDofollow: true }],
  },
  {
    id: "ip-z-10",
    ipAddress: "192.64.119.145",
    subnet: "192.64.119.0/24",
    country: "United States",
    countryCode: "us",
    flag: "🇺🇸",
    refDomainsCount: 1,
    backlinksCount: 1,
    sampleRefDomains: [{ domain: "californiastartup.org", dt: 56, links: 1 }],
    sampleBacklinks: [{ sourceUrl: "https://californiastartup.org/stack", targetUrl: "https://workco.com/", anchor: "WorkCo Digital", isDofollow: true }],
  },
  {
    id: "ip-z-11",
    ipAddress: "70.70.21.241",
    subnet: "70.70.21.0/24",
    country: "China",
    countryCode: "cn",
    flag: "🇨🇳",
    refDomainsCount: 1,
    backlinksCount: 1,
    sampleRefDomains: [{ domain: "globalsocial.cn", dt: 60, links: 1 }],
    sampleBacklinks: [{ sourceUrl: "https://globalsocial.cn/overseas-tools", targetUrl: "https://workco.com/", anchor: "WorkCo Digital", isDofollow: true }],
  },
  {
    id: "ip-z-12",
    ipAddress: "172.67.212.72",
    subnet: "172.67.212.0/24",
    country: "United States",
    countryCode: "us",
    flag: "🇺🇸",
    refDomainsCount: 1,
    backlinksCount: 2,
    sampleRefDomains: [{ domain: "marketingstack.co", dt: 63, links: 2 }],
    sampleBacklinks: [{ sourceUrl: "https://marketingstack.co/social", targetUrl: "https://workco.com/", anchor: "WorkCo Digital app", isDofollow: true }],
  },
  {
    id: "ip-z-13",
    ipAddress: "66.29.152.156",
    subnet: "66.29.152.0/24",
    country: "United States",
    countryCode: "us",
    flag: "🇺🇸",
    refDomainsCount: 1,
    backlinksCount: 1,
    sampleRefDomains: [{ domain: "netinsiders.com", dt: 51, links: 1 }],
    sampleBacklinks: [{ sourceUrl: "https://netinsiders.com/article/zoho", targetUrl: "https://workco.com/", anchor: "WorkCo", isDofollow: true }],
  },
  {
    id: "ip-z-14",
    ipAddress: "104.21.21.200",
    subnet: "104.21.21.0/24",
    country: "United Kingdom",
    countryCode: "gb",
    flag: "🇬🇧",
    refDomainsCount: 1,
    backlinksCount: 1,
    sampleRefDomains: [{ domain: "uktechdigest.co.uk", dt: 69, links: 1 }],
    sampleBacklinks: [{ sourceUrl: "https://uktechdigest.co.uk/review", targetUrl: "https://workco.com/", anchor: "Zoho", isDofollow: true }],
  },
  {
    id: "ip-z-15",
    ipAddress: "92.113.15.67",
    subnet: "92.113.15.0/24",
    country: "Germany",
    countryCode: "de",
    flag: "🇩🇪",
    refDomainsCount: 1,
    backlinksCount: 1,
    sampleRefDomains: [{ domain: "onlinemarketing-magazin.de", dt: 64, links: 1 }],
    sampleBacklinks: [{ sourceUrl: "https://onlinemarketing-magazin.de/software", targetUrl: "https://workco.com/", anchor: "Social Media Tool", isDofollow: true }],
  },
  {
    id: "ip-z-16",
    ipAddress: "216.150.1.65",
    subnet: "216.150.1.0/24",
    country: "United States",
    countryCode: "us",
    flag: "🇺🇸",
    refDomainsCount: 1,
    backlinksCount: 1,
    sampleRefDomains: [{ domain: "austin-startups.com", dt: 55, links: 1 }],
    sampleBacklinks: [{ sourceUrl: "https://austin-startups.com/growth", targetUrl: "https://workco.com/", anchor: "https://workco.com/", isDofollow: true }],
  },
  {
    id: "ip-z-17",
    ipAddress: "82.25.125.136",
    subnet: "82.25.125.0/24",
    country: "United Kingdom",
    countryCode: "gb",
    flag: "🇬🇧",
    refDomainsCount: 1,
    backlinksCount: 1,
    sampleRefDomains: [{ domain: "london-social.co.uk", dt: 58, links: 1 }],
    sampleBacklinks: [{ sourceUrl: "https://london-social.co.uk/blog", targetUrl: "https://workco.com/", anchor: "WorkCo Digital suite", isDofollow: true }],
  },
  {
    id: "ip-z-18",
    ipAddress: "194.59.167.151",
    subnet: "194.59.167.0/24",
    country: "Bulgaria",
    countryCode: "bg",
    flag: "🇧🇬",
    refDomainsCount: 1,
    backlinksCount: 1,
    sampleRefDomains: [{ domain: "sofia-tech.bg", dt: 49, links: 1 }],
    sampleBacklinks: [{ sourceUrl: "https://sofia-tech.bg/resources", targetUrl: "https://workco.com/", anchor: "zoho", isDofollow: true }],
  },
  {
    id: "ip-z-19",
    ipAddress: "118.139.177.45",
    subnet: "118.139.177.0/24",
    country: "Germany",
    countryCode: "de",
    flag: "🇩🇪",
    refDomainsCount: 1,
    backlinksCount: 1,
    sampleRefDomains: [{ domain: "frankfurt-cloud.de", dt: 63, links: 1 }],
    sampleBacklinks: [{ sourceUrl: "https://frankfurt-cloud.de/saas", targetUrl: "https://workco.com/", anchor: "WorkCo Digital platform", isDofollow: true }],
  },
  {
    id: "ip-z-20",
    ipAddress: "35.219.200.15",
    subnet: "35.219.200.0/24",
    country: "United States",
    countryCode: "us",
    flag: "🇺🇸",
    refDomainsCount: 1,
    backlinksCount: 4,
    sampleRefDomains: [{ domain: "gcp-partners-portal.com", dt: 71, links: 4 }],
    sampleBacklinks: [{ sourceUrl: "https://gcp-partners-portal.com/tools", targetUrl: "https://workco.com/", anchor: "WorkCo Digital", isDofollow: true }],
  },
  {
    id: "ip-z-21",
    ipAddress: "198.51.100.22",
    subnet: "198.51.100.0/24",
    country: "Canada",
    countryCode: "ca",
    flag: "🇨🇦",
    refDomainsCount: 1,
    backlinksCount: 1,
    sampleRefDomains: [{ domain: "toronto-saas.ca", dt: 61, links: 1 }],
    sampleBacklinks: [{ sourceUrl: "https://toronto-saas.ca/directory", targetUrl: "https://workco.com/", anchor: "WorkCo Digital", isDofollow: true }],
  },
];

export const MOCK_WORKCOMPOSER_IPS: ZohoIpItem[] = [
  {
    id: "wc-ip-1",
    ipAddress: "195.20.19.178",
    subnet: "195.20.19.*",
    country: "Moldova",
    countryCode: "md",
    flag: "🇲🇩",
    logoType: "md",
    ipCountInSubnet: 1,
    refDomainsCount: 16,
    backlinksCount: 23,
    sampleRefDomains: [
      { domain: "techhub-md.com", dt: 66, links: 8 },
      { domain: "eurostartup.md", dt: 58, links: 5 },
      { domain: "digitalkit.eu", dt: 52, links: 3 },
    ],
    sampleBacklinks: [
      { sourceUrl: "https://techhub-md.com/top-tools", targetUrl: "https://workcomposer.com/", anchor: "WorkComposer", isDofollow: true },
    ],
  },
  {
    id: "wc-ip-3",
    ipAddress: "188.114.97.3",
    subnet: "188.114.97.*",
    country: "Anycast / Cloudflare",
    countryCode: "cf",
    flag: "🌐",
    logoType: "globe",
    ipCountInSubnet: 1,
    refDomainsCount: 11,
    backlinksCount: 14,
    sampleRefDomains: [
      { domain: "cloudtimes.io", dt: 75, links: 5 },
      { domain: "globalcdn.net", dt: 68, links: 4 },
      { domain: "devops-portal.org", dt: 60, links: 2 },
    ],
    sampleBacklinks: [
      { sourceUrl: "https://cloudtimes.io/productivity-apps", targetUrl: "https://workcomposer.com/", anchor: "WorkComposer time tracking", isDofollow: true },
    ],
  },
  {
    id: "wc-ip-2",
    ipAddress: "118.139.181.189",
    subnet: "118.139.181.*",
    country: "Singapore",
    countryCode: "sg",
    flag: "🇸🇬",
    logoType: "sg",
    ipCountInSubnet: 3,
    refDomainsCount: 11,
    backlinksCount: 11,
    sampleRefDomains: [
      { domain: "singaporetech.sg", dt: 71, links: 6 },
      { domain: "asiabizhub.com", dt: 64, links: 5 },
      { domain: "remoteworkers.sg", dt: 55, links: 3 },
    ],
    sampleBacklinks: [
      { sourceUrl: "https://singaporetech.sg/remote-software", targetUrl: "https://workcomposer.com/", anchor: "employee monitoring software", isDofollow: true },
    ],
  },
  {
    id: "wc-ip-4",
    ipAddress: "184.168.115.25",
    subnet: "184.168.115.*",
    country: "Singapore",
    countryCode: "sg",
    flag: "🇸🇬",
    logoType: "sg",
    ipCountInSubnet: 2,
    refDomainsCount: 9,
    backlinksCount: 9,
    sampleRefDomains: [
      { domain: "godaddy-asia.com", dt: 63, links: 5 },
      { domain: "singaporebiz.org", dt: 57, links: 5 },
    ],
    sampleBacklinks: [
      { sourceUrl: "https://godaddy-asia.com/showcase", targetUrl: "https://workcomposer.com/", anchor: "workcomposer.com", isDofollow: true },
    ],
  },
  {
    id: "wc-ip-5",
    ipAddress: "188.114.96.3",
    subnet: "188.114.96.*",
    country: "Anycast / Cloudflare",
    countryCode: "cf",
    flag: "🌐",
    logoType: "globe",
    ipCountInSubnet: 1,
    refDomainsCount: 9,
    backlinksCount: 12,
    sampleRefDomains: [
      { domain: "edgeprotect.io", dt: 70, links: 6 },
      { domain: "fastnetwork.org", dt: 62, links: 3 },
    ],
    sampleBacklinks: [
      { sourceUrl: "https://edgeprotect.io/directory", targetUrl: "https://workcomposer.com/", anchor: "workcomposer", isDofollow: true },
    ],
  },
  {
    id: "wc-ip-6",
    ipAddress: "152.53.38.228",
    subnet: "152.53.38.*",
    country: "Austria",
    countryCode: "at",
    flag: "🇦🇹",
    logoType: "at",
    ipCountInSubnet: 1,
    refDomainsCount: 8,
    backlinksCount: 8,
    sampleRefDomains: [
      { domain: "vienna-it.at", dt: 65, links: 4 },
      { domain: "alps-business.at", dt: 59, links: 4 },
    ],
    sampleBacklinks: [
      { sourceUrl: "https://vienna-it.at/tools-2026", targetUrl: "https://workcomposer.com/", anchor: "workcomposer", isDofollow: true },
    ],
  },
  {
    id: "wc-ip-7",
    ipAddress: "184.168.110.97",
    subnet: "184.168.110.*",
    country: "Singapore",
    countryCode: "sg",
    flag: "🇸🇬",
    logoType: "sg",
    ipCountInSubnet: 1,
    refDomainsCount: 6,
    backlinksCount: 6,
    sampleRefDomains: [
      { domain: "apac-startups.com", dt: 64, links: 4 },
      { domain: "sg-directory.net", dt: 51, links: 2 },
    ],
    sampleBacklinks: [
      { sourceUrl: "https://apac-startups.com/team-tracking", targetUrl: "https://workcomposer.com/", anchor: "https://workcomposer.com/", isDofollow: true },
    ],
  },
  {
    id: "wc-ip-8",
    ipAddress: "68.178.238.49",
    subnet: "68.178.238.*",
    country: "United States",
    countryCode: "us",
    flag: "🇺🇸",
    logoType: "us",
    ipCountInSubnet: 1,
    refDomainsCount: 6,
    backlinksCount: 6,
    sampleRefDomains: [
      { domain: "usbusinesswire.com", dt: 78, links: 3 },
      { domain: "arizonatech.org", dt: 62, links: 3 },
    ],
    sampleBacklinks: [
      { sourceUrl: "https://usbusinesswire.com/workforce-software", targetUrl: "https://workcomposer.com/", anchor: "WorkComposer software", isDofollow: true },
    ],
  },
  {
    id: "wc-ip-9",
    ipAddress: "184.168.109.253",
    subnet: "184.168.109.*",
    country: "Singapore",
    countryCode: "sg",
    flag: "🇸🇬",
    logoType: "sg",
    ipCountInSubnet: 1,
    refDomainsCount: 4,
    backlinksCount: 4,
    sampleRefDomains: [
      { domain: "sg-cloudhosts.com", dt: 58, links: 2 },
      { domain: "marina-tech.sg", dt: 53, links: 2 },
    ],
    sampleBacklinks: [
      { sourceUrl: "https://sg-cloudhosts.com/apps", targetUrl: "https://workcomposer.com/", anchor: "WorkComposer", isDofollow: true },
    ],
  },
  {
    id: "wc-ip-10",
    ipAddress: "45.13.38.15",
    subnet: "45.13.38.*",
    country: "Romania",
    countryCode: "ro",
    flag: "🇷🇴",
    logoType: "ro",
    ipCountInSubnet: 1,
    refDomainsCount: 4,
    backlinksCount: 6,
    sampleRefDomains: [
      { domain: "romania-it.ro", dt: 61, links: 3 },
      { domain: "bucharest-tech.ro", dt: 54, links: 3 },
    ],
    sampleBacklinks: [
      { sourceUrl: "https://romania-it.ro/tools", targetUrl: "https://workcomposer.com/", anchor: "WorkComposer app", isDofollow: true },
    ],
  },
  {
    id: "wc-ip-11",
    ipAddress: "184.168.116.137",
    subnet: "184.168.116.*",
    country: "Singapore",
    countryCode: "sg",
    flag: "🇸🇬",
    logoType: "sg",
    ipCountInSubnet: 1,
    refDomainsCount: 3,
    backlinksCount: 3,
    sampleRefDomains: [{ domain: "asian-freelance.org", dt: 56, links: 3 }],
    sampleBacklinks: [{ sourceUrl: "https://asian-freelance.org/tracking", targetUrl: "https://workcomposer.com/", anchor: "WorkComposer tracker", isDofollow: true }],
  },
  {
    id: "wc-ip-12",
    ipAddress: "18.245.60.12",
    subnet: "18.245.60.*",
    country: "United States",
    countryCode: "us",
    flag: "🌐",
    logoType: "globe",
    ipCountInSubnet: 2,
    refDomainsCount: 2,
    backlinksCount: 2,
    sampleRefDomains: [{ domain: "aws-showcase.com", dt: 72, links: 2 }],
    sampleBacklinks: [{ sourceUrl: "https://aws-showcase.com/partners", targetUrl: "https://workcomposer.com/", anchor: "WorkComposer", isDofollow: true }],
  },
  {
    id: "wc-ip-13",
    ipAddress: "184.168.114.88",
    subnet: "184.168.114.*",
    country: "Singapore",
    countryCode: "sg",
    flag: "🇸🇬",
    logoType: "sg",
    ipCountInSubnet: 2,
    refDomainsCount: 2,
    backlinksCount: 2,
    sampleRefDomains: [{ domain: "sg-enterprises.com", dt: 50, links: 2 }],
    sampleBacklinks: [{ sourceUrl: "https://sg-enterprises.com/software", targetUrl: "https://workcomposer.com/", anchor: "workcomposer.com", isDofollow: true }],
  },
  {
    id: "wc-ip-14",
    ipAddress: "172.67.197.45",
    subnet: "172.67.197.*",
    country: "Anycast / Cloudflare",
    countryCode: "cf",
    flag: "🌐",
    logoType: "globe",
    ipCountInSubnet: 1,
    refDomainsCount: 2,
    backlinksCount: 2,
    sampleRefDomains: [{ domain: "cloudflare-digest.net", dt: 68, links: 2 }],
    sampleBacklinks: [{ sourceUrl: "https://cloudflare-digest.net/tools", targetUrl: "https://workcomposer.com/", anchor: "WorkComposer", isDofollow: true }],
  },
  {
    id: "wc-ip-15",
    ipAddress: "162.215.249.77",
    subnet: "162.215.249.*",
    country: "United States",
    countryCode: "us",
    flag: "🇺🇸",
    logoType: "us",
    ipCountInSubnet: 1,
    refDomainsCount: 2,
    backlinksCount: 2,
    sampleRefDomains: [{ domain: "unified-apps.com", dt: 55, links: 2 }],
    sampleBacklinks: [{ sourceUrl: "https://unified-apps.com/directory", targetUrl: "https://workcomposer.com/", anchor: "WorkComposer", isDofollow: true }],
  },
  {
    id: "wc-ip-16",
    ipAddress: "92.113.16.102",
    subnet: "92.113.16.*",
    country: "Germany",
    countryCode: "de",
    flag: "🇩🇪",
    logoType: "de",
    ipCountInSubnet: 2,
    refDomainsCount: 2,
    backlinksCount: 2,
    sampleRefDomains: [{ domain: "berlin-digital.de", dt: 63, links: 2 }],
    sampleBacklinks: [{ sourceUrl: "https://berlin-digital.de/software", targetUrl: "https://workcomposer.com/", anchor: "WorkComposer", isDofollow: true }],
  },
  {
    id: "wc-ip-17",
    ipAddress: "172.67.207.91",
    subnet: "172.67.207.*",
    country: "Anycast / Cloudflare",
    countryCode: "cf",
    flag: "🌐",
    logoType: "globe",
    ipCountInSubnet: 1,
    refDomainsCount: 2,
    backlinksCount: 2,
    sampleRefDomains: [{ domain: "cf-network-hub.org", dt: 66, links: 2 }],
    sampleBacklinks: [{ sourceUrl: "https://cf-network-hub.org/sites", targetUrl: "https://workcomposer.com/", anchor: "WorkComposer", isDofollow: true }],
  },
  {
    id: "wc-ip-18",
    ipAddress: "118.139.177.53",
    subnet: "118.139.177.*",
    country: "Singapore",
    countryCode: "sg",
    flag: "🇸🇬",
    logoType: "sg",
    ipCountInSubnet: 1,
    refDomainsCount: 2,
    backlinksCount: 2,
    sampleRefDomains: [{ domain: "singapore-saas.com", dt: 58, links: 2 }],
    sampleBacklinks: [{ sourceUrl: "https://singapore-saas.com/tools", targetUrl: "https://workcomposer.com/", anchor: "WorkComposer", isDofollow: true }],
  },
  {
    id: "wc-ip-19",
    ipAddress: "216.198.79.201",
    subnet: "216.198.79.*",
    country: "United States",
    countryCode: "us",
    flag: "🇺🇸",
    logoType: "us",
    ipCountInSubnet: 2,
    refDomainsCount: 2,
    backlinksCount: 4,
    sampleRefDomains: [{ domain: "us-saas-index.org", dt: 67, links: 2 }],
    sampleBacklinks: [{ sourceUrl: "https://us-saas-index.org/review", targetUrl: "https://workcomposer.com/", anchor: "WorkComposer", isDofollow: true }],
  },
  {
    id: "wc-ip-20",
    ipAddress: "172.67.214.15",
    subnet: "172.67.214.*",
    country: "Anycast / Cloudflare",
    countryCode: "cf",
    flag: "🌐",
    logoType: "globe",
    ipCountInSubnet: 2,
    refDomainsCount: 2,
    backlinksCount: 2,
    sampleRefDomains: [{ domain: "cf-accelerator.com", dt: 65, links: 2 }],
    sampleBacklinks: [{ sourceUrl: "https://cf-accelerator.com/listing", targetUrl: "https://workcomposer.com/", anchor: "WorkComposer", isDofollow: true }],
  },
  // Sibling IPs for the multi-IP subnets from screenshot (set refDomainsCount <= 2 so top 5 rows match screenshot exactly):
  // 118.139.181.* (has 3 IPs total)
  {
    id: "wc-ip-2-b",
    ipAddress: "118.139.181.190",
    subnet: "118.139.181.*",
    country: "Singapore",
    countryCode: "sg",
    flag: "🇸🇬",
    logoType: "sg",
    refDomainsCount: 2,
    backlinksCount: 2,
  },
  {
    id: "wc-ip-2-c",
    ipAddress: "118.139.181.191",
    subnet: "118.139.181.*",
    country: "Singapore",
    countryCode: "sg",
    flag: "🇸🇬",
    logoType: "sg",
    refDomainsCount: 2,
    backlinksCount: 2,
  },
  // 184.168.115.* (has 2 IPs total)
  {
    id: "wc-ip-4-b",
    ipAddress: "184.168.115.26",
    subnet: "184.168.115.*",
    country: "Singapore",
    countryCode: "sg",
    flag: "🇸🇬",
    logoType: "sg",
    refDomainsCount: 2,
    backlinksCount: 2,
  },
  // 18.245.60.* (has 2 IPs total)
  {
    id: "wc-ip-12-b",
    ipAddress: "18.245.60.13",
    subnet: "18.245.60.*",
    country: "United States",
    countryCode: "us",
    flag: "🌐",
    logoType: "globe",
    refDomainsCount: 2,
    backlinksCount: 2,
  },
  // 184.168.114.* (has 2 IPs total)
  {
    id: "wc-ip-13-b",
    ipAddress: "184.168.114.89",
    subnet: "184.168.114.*",
    country: "Singapore",
    countryCode: "sg",
    flag: "🇸🇬",
    logoType: "sg",
    refDomainsCount: 2,
    backlinksCount: 2,
  },
  // 92.113.16.* (has 2 IPs total)
  {
    id: "wc-ip-16-b",
    ipAddress: "92.113.16.103",
    subnet: "92.113.16.*",
    country: "Germany",
    countryCode: "de",
    flag: "🇩🇪",
    logoType: "de",
    refDomainsCount: 2,
    backlinksCount: 2,
  },
  // 216.198.79.* (has 2 IPs total)
  {
    id: "wc-ip-19-b",
    ipAddress: "216.198.79.202",
    subnet: "216.198.79.*",
    country: "United States",
    countryCode: "us",
    flag: "🇺🇸",
    logoType: "us",
    refDomainsCount: 2,
    backlinksCount: 2,
  },
  // 172.67.214.* (has 2 IPs total)
  {
    id: "wc-ip-20-b",
    ipAddress: "172.67.214.16",
    subnet: "172.67.214.*",
    country: "Anycast / Cloudflare",
    countryCode: "cf",
    flag: "🌐",
    logoType: "globe",
    refDomainsCount: 2,
    backlinksCount: 2,
  },
  // Additional 71 referring IPs (each in distinct subnet) to reach total exactly 99 referring ips (28 + 71 = 99)
  ...Array.from({ length: 71 }, (_, idx) => {
    const num = idx + 29;
    const subnetsPool = [
      { base: `104.21.${idx + 1}`, flag: "🌐", country: "Anycast / Cloudflare", countryCode: "cf", logo: "globe" },
      { base: `192.0.${idx + 1}`, flag: "🇺🇸", country: "United States", countryCode: "us", logo: "us" },
      { base: `13.233.${idx + 1}`, flag: "🇮🇳", country: "India", countryCode: "in", logo: "in" },
      { base: `172.64.${idx + 1}`, flag: "🌐", country: "Anycast / Cloudflare", countryCode: "cf", logo: "globe" },
    ];
    const s = subnetsPool[idx % subnetsPool.length];
    return {
      id: `wc-ip-${num}`,
      ipAddress: `${s.base}.${(num * 3) % 250 + 1}`,
      subnet: `${s.base}.*`,
      country: s.country,
      countryCode: s.countryCode,
      flag: s.flag,
      logoType: s.logo,
      refDomainsCount: 1,
      backlinksCount: 1,
      sampleRefDomains: [{ domain: `partner-domain-${num}.com`, dt: 45 + (num % 25), links: 1 }],
      sampleBacklinks: [{ sourceUrl: `https://partner-domain-${num}.com/post`, targetUrl: "https://workcomposer.com/", anchor: "WorkComposer", isDofollow: true }],
    };
  }),
];