/**
 * Complete Real SE Ranking Global Application Wrap Data (window.appWrapData)
 * Extracted directly from live SE Ranking production DOM & runtime state.
 */

export const appWrapData = {
  account: {
    id: 5269343,
    setting_date_format: "%b-%d %Y",
    setting_date_format_short: "%b-%d",
    timezone_offset_seconds: 18000,
    number_format: { thous_sep: ",", decimal_sep: "." },
    first_day_of_week: 1,
    email: "suraj.vishwakarma@gvilab.com",
    admin_email: null,
    lang: "en",
    full_name: "Suraj Vishwakarma",
    first_name: "Suraj",
    last_name: "Vishwakarma",
    avatar: {
      url: "https://online.seranking.com/files/public/avatar/upload-icon.png",
      is_custom: false,
    },
    is_admin: false,
    is_super_admin: false,
    is_affiliate_manager: false,
    is_sub_account: false,
    is_sub_account_email_notification_settings_editing_allowed: false,
    is_demo: false,
    is_advanced_demo: false,
    is_read_only: false,
    is_client: false,
    is_guest: false,
    is_support_login: false,
    is_remote_support: false,
    is_hide_volume: false,
    is_wallet_enabled: true,
    is_expired_trial: false,
    is_trial: false,
    is_new_lead: false,
    is_manual: false,
    is_yandex_allowed: false,
    is_research_trial_bonus_enabled: false,
    is_legacy_license: false,
    permissions: [
      "overview",
      "add_website",
      "traffic",
      "visitors",
      "pages",
      "conversions",
      "snippets",
      "google_search_console",
      "seo_potencial",
      "analytics_connect_ga_gsc",
      "main_competitors",
      "top10",
      "top100",
      "all_competitors",
      "share_of_voice",
      "seo_checklist",
      "audit_report",
      "web_monitoring",
      "backlinks",
      "tools_local_marketing",
      "local_marketing_add_locations",
      "report_manual",
      "report_sheduled",
      "report_template",
      "tools_research_competitor",
      "tools_research_keywords",
      "tools_backlinks_explorer",
      "tools_seochecker",
      "tools_single_page_audit",
      "tools_serp_analyzer_audit",
      "tools_key_suggestion",
      "tools_key_volume",
      "tools_chek_index",
      "tools_clustering",
      "tools_leads_generator",
      "api",
      "whitelabel",
      "client_accounts",
      "api_v4",
      "add_keyword_to_research",
      "audit_settings",
      "backlinks_builder",
      "content_editor",
      "content_planner",
      "resource_access",
      "insights",
      "guest_links",
      "llm_research",
      "data_api",
      "llm_rankings",
      "analytics_and_traffic",
      "competitors",
      "audit",
      "account_reports",
      "keytools",
    ],
    is_business: true,
    is_google_aio_enabled: true,
    is_aio_research_enabled: true,
    is_llm_enabled: true,
    is_research_llm_v2_enabled: true,
  },
  active_project_id: 12960641,
  active_project: {
    site_id: 12960641,
    site_title: "zohosocial.com",
    site_name: "zohosocial.com",
    site_color: "#04fb63",
    domain: "zohosocial.com",
    domain_encoded: "zohosocial.com",
  },
  breadcrumbs: {
    items: [
      { text: "zohosocial.com", href: "/rankings" },
      { text: "Project Overview", href: "/project-overview" },
    ],
  },
  trial_notification: {
    trial_type: "trial",
    days_left: 12,
  },
  trial_bonus_popup: {
    seconds_left: 244980,
    percent: 10,
    coupon: "ABT10NK",
    learn_more_url: "https://seranking.com/personal-se-ranking-discount-10.html",
  },
  subscription_info: {
    current_plan_version: 1,
    license_is_cancelled: false,
    license_is_auto_renewal: false,
    license_package: "personal",
    license_is_expired: false,
    reactivation_new: false,
  },
  keyword_manager: {
    has_access: true,
    has_plan_access: true,
    total_lists_limit: 2147483647,
    total_keywords_available: 120000,
    check_price: 0,
    tariff_price: 1,
  },
  notifications: {
    categories: [
      { key: 3, title: "Product changes", color: "yellow", unread: 0 },
      { key: 2, title: "Important messages", color: "red", unread: 1 },
      { key: 1, title: "System messages", color: "green", unread: 0 },
    ],
    icon_color: "red",
    show_updates_popup: false,
    unread_total: 1,
  },
  site_notes: {
    notes_count: 46,
  },
  currency: {
    by_ip: "USD",
    list: {
      USD: { symbol: "$", fullname: "Dollar", code: "USD", currency_iso_number: 840 },
      EUR: { symbol: "€", fullname: "Euro", code: "EUR", currency_iso_number: 978 },
      GBP: { symbol: "£", fullname: "English pound", code: "GBP", currency_iso_number: 826 },
      AUD: { symbol: "A$", fullname: "Australian dollar", code: "AUD", currency_iso_number: 36 },
      JPY: { symbol: "¥", fullname: "Japanese yen", code: "JPY", currency_iso_number: 392 },
    },
  },
  navigation: {
    user_menu: [
      { text: "Settings", href: "/settings", icon: "settings" },
      { text: "Users", href: "/users", icon: "users" },
      { text: "White Label", href: "/settings/white-label", icon: "whitelabel" },
      { text: "Billing", href: "/billing", icon: "subscription" },
      { text: "Bonus Offers", href: "/bonus-offers", icon: "earn_keywords" },
      { text: "Affiliate Program", href: "/affiliate", icon: "affiliate" },
      { text: "Log Out", href: "/logout", icon: "logout" },
    ],
    project_menu: [
      { text: "Project Overview", href: "/project-overview", icon: "project_overview" },
      {
        text: "Rankings",
        href: "/rankings",
        icon: "rankings",
        submenu: [
          { text: "Summary", href: "/rankings" },
          { text: "Detailed", href: "/rankings?tab=detailed" },
          { text: "Historical data", href: "/rankings?tab=history" },
        ],
      },
      {
        text: "Analytics & Traffic",
        href: "/analytics",
        icon: "analytics",
        submenu: [
          { text: "Overview", href: "/analytics" },
          { text: "Traffic", href: "/analytics?tab=traffic" },
          { text: "Snippets", href: "/analytics?tab=snippets" },
          { text: "Google Search Console Data", href: "/analytics?tab=gsc" },
          { text: "SEO potential", href: "/analytics?tab=potential" },
        ],
      },
      {
        text: "My Competitors",
        href: "/competitors",
        icon: "competitors",
        submenu: [
          { text: "Added Competitors", href: "/competitors" },
          { text: "SERP Competitors", href: "/competitors?tab=top100" },
          { text: "Share of Voice", href: "/competitors?tab=sov" },
          { text: "Visibility Rating", href: "/competitors?tab=visibility" },
        ],
      },
      {
        text: "AI Results Tracker",
        href: "/ai-results-tracker",
        icon: "rankings_ai_overview",
        beta: true,
        labelColor: "#145EA8",
        labelBackgroundColor: "#E3EFFA",
        submenu: [
          { text: "Rankings", href: "/ai-results-tracker" },
          { text: "Competitors", href: "/ai-results-tracker?tab=competitors" },
          { text: "Sources", href: "/ai-results-tracker?tab=sources" },
        ],
      },
      { text: "Insights", href: "/insights", icon: "insights" },
      { text: "Backlink Checker", href: "/backlinks", icon: "backlinks_explorer" },
      { text: "Marketing Plan", href: "/marketing-plan", icon: "checklist" },
      {
        text: "Website Audit",
        href: "/website-audit",
        icon: "audit",
        submenu: [
          { text: "Overview", href: "/website-audit?tab=overview" },
          { text: "Issue Report", href: "/website-audit?tab=issues" },
          { text: "Crawled Pages", href: "/website-audit?tab=pages" },
          { text: "Found Resources", href: "/website-audit?tab=resources" },
          { text: "Found Links", href: "/website-audit?tab=links" },
          { text: "Crawl Comparison", href: "/website-audit?tab=compare" },
        ],
      },
      { text: "Page Changes Monitor", href: "/page-changes", icon: "web_monitor" },
      {
        text: "Backlink Monitor",
        href: "/backlinks-monitor",
        icon: "backlinks_monitor",
        submenu: [
          { text: "Backlinks", href: "/backlinks-monitor" },
          { text: "Domains", href: "/backlinks-monitor?tab=domains" },
          { text: "Anchor Texts", href: "/backlinks-monitor?tab=anchors" },
          { text: "Pages", href: "/backlinks-monitor?tab=pages" },
          { text: "IPs/Subnets", href: "/backlinks-monitor?tab=ips" },
          { text: "Disavow", href: "/backlinks-monitor?tab=disavow" },
        ],
      },
      { text: "Project settings", href: "/settings", icon: "settings" },
    ],
    footer_menu: [
      { text: "Report a bug", href: "#", action: "bug_report" },
      { text: "Affiliates", href: "/affiliate" },
      { text: "API", href: "/api-docs" },
      { text: "What's new", href: "/whats-new" },
      { text: "Help", href: "/help" },
    ],
  },
};

// Client-side hydration
if (typeof window !== "undefined") {
  (window as any).appWrapData = appWrapData;
}
